<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; 표본으로 미지의 모수 추정하기 – JAMOVI로 배우는 통계학</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-Hypothesis-testing.html" rel="next">
<link href="./07-Introduction-to-probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="text/x-mathjax-config">

  MathJax.Hub.Config({

    tex2jax: {

      inlineMath: [ ['$','$'], ["\\(","\\)"] ],

      displayMath: [ ['S$','S$'], ["\\[","\\]"] ]

      processEscapes: true

    }

  });

</script>



<!-- Google tag (gtag.js) -->

<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-01849X2TQ1"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());



  gtag('config', 'G-01849X2TQ1');

</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="8&nbsp; 표본으로 미지의 모수 추정하기 – JAMOVI로 배우는 통계학">
<meta property="og:description" content="">
<meta property="og:site_name" content="JAMOVI로 배우는 통계학">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Prelude-Part-IV.html">통계 이론</a></li><li class="breadcrumb-item"><a href="./08-Estimating-unknown-quantities-from-a-sample.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">표본으로 미지의 모수 추정하기</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">JAMOVI로 배우는 통계학</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/kilhwan/jamovi/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">역자 서문</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">시작하며</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Why-do-we-learn-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">왜 통계를 배워야 하는가</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-A-brief-introduction-to-research-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">연구 설계에 대한 간략한 소개</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">jamovi 소개</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Getting-started-with-jamovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">jamovi 시작하기</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">데이터 다루기</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Descriptive-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">기술 통계량</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Drawing-graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">그래프 그리기</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Pragmatic-matters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">데이터 조작</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">통계 이론</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Prelude-Part-IV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">들어가며</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Introduction-to-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">확률이란?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Estimating-unknown-quantities-from-a-sample.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">표본으로 미지의 모수 추정하기</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">가설 검정</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">통계 기법</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Categorical-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">범주형 데이터 분석</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Comparing-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">두 평균 비교하기</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Correlation-and-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">상관관계와 선형회귀</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Comparing-several-means-one-way-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">여러 평균 비교하기 - 일원분산분석</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-Factorial-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">요인분산분석</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-Factor-Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">요인분석</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">마무리하며, 대안과 전망</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Bayesian-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">베이지안 통계학</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">에필로그</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#표본-모집단-및-표본추출" id="toc-표본-모집단-및-표본추출" class="nav-link active" data-scroll-target="#표본-모집단-및-표본추출"><span class="header-section-number">8.1</span> 표본, 모집단 및 표본추출</a>
  <ul class="collapse">
  <li><a href="#모집단-정의하기" id="toc-모집단-정의하기" class="nav-link" data-scroll-target="#모집단-정의하기"><span class="header-section-number">8.1.1</span> 모집단 정의하기</a></li>
  <li><a href="#단순-무작위-표본" id="toc-단순-무작위-표본" class="nav-link" data-scroll-target="#단순-무작위-표본"><span class="header-section-number">8.1.2</span> 단순 무작위 표본</a></li>
  <li><a href="#대부분의-표본은-단순-무작위-표본이-아니다" id="toc-대부분의-표본은-단순-무작위-표본이-아니다" class="nav-link" data-scroll-target="#대부분의-표본은-단순-무작위-표본이-아니다"><span class="header-section-number">8.1.3</span> 대부분의 표본은 단순 무작위 표본이 아니다</a></li>
  <li><a href="#단순-무작위-표본이-아니면-얼마나-문제가-될까" id="toc-단순-무작위-표본이-아니면-얼마나-문제가-될까" class="nav-link" data-scroll-target="#단순-무작위-표본이-아니면-얼마나-문제가-될까"><span class="header-section-number">8.1.4</span> 단순 무작위 표본이 아니면 얼마나 문제가 될까?</a></li>
  <li><a href="#모집단-모수와-표본-통계량" id="toc-모집단-모수와-표본-통계량" class="nav-link" data-scroll-target="#모집단-모수와-표본-통계량"><span class="header-section-number">8.1.5</span> 모집단 모수와 표본 통계량</a></li>
  </ul></li>
  <li><a href="#대수의-법칙" id="toc-대수의-법칙" class="nav-link" data-scroll-target="#대수의-법칙"><span class="header-section-number">8.2</span> 대수의 법칙</a></li>
  <li><a href="#표본-분포와-중심극한정리" id="toc-표본-분포와-중심극한정리" class="nav-link" data-scroll-target="#표본-분포와-중심극한정리"><span class="header-section-number">8.3</span> 표본 분포와 중심극한정리</a>
  <ul class="collapse">
  <li><a href="#sec-Sampling-distribution-of-the-mean" id="toc-sec-Sampling-distribution-of-the-mean" class="nav-link" data-scroll-target="#sec-Sampling-distribution-of-the-mean"><span class="header-section-number">8.3.1</span> 평균의 표본 분포</a></li>
  <li><a href="#모든-표본-통계량에는-표본-분포가-존재한다" id="toc-모든-표본-통계량에는-표본-분포가-존재한다" class="nav-link" data-scroll-target="#모든-표본-통계량에는-표본-분포가-존재한다"><span class="header-section-number">8.3.2</span> 모든 표본 통계량에는 표본 분포가 존재한다!</a></li>
  <li><a href="#sec-The-central-limit-theorem" id="toc-sec-The-central-limit-theorem" class="nav-link" data-scroll-target="#sec-The-central-limit-theorem"><span class="header-section-number">8.3.3</span> 중심극한정리</a></li>
  </ul></li>
  <li><a href="#모집단-모수-추정하기" id="toc-모집단-모수-추정하기" class="nav-link" data-scroll-target="#모집단-모수-추정하기"><span class="header-section-number">8.4</span> 모집단 모수 추정하기</a>
  <ul class="collapse">
  <li><a href="#모집단-평균-추정하기" id="toc-모집단-평균-추정하기" class="nav-link" data-scroll-target="#모집단-평균-추정하기"><span class="header-section-number">8.4.1</span> 모집단 평균 추정하기</a></li>
  <li><a href="#모집단-표준편차-추정하기" id="toc-모집단-표준편차-추정하기" class="nav-link" data-scroll-target="#모집단-표준편차-추정하기"><span class="header-section-number">8.4.2</span> 모집단 표준편차 추정하기</a></li>
  </ul></li>
  <li><a href="#sec-Estimating-a-confidence-interval" id="toc-sec-Estimating-a-confidence-interval" class="nav-link" data-scroll-target="#sec-Estimating-a-confidence-interval"><span class="header-section-number">8.5</span> 신뢰구간 추정</a>
  <ul class="collapse">
  <li><a href="#신뢰구간-해석하기" id="toc-신뢰구간-해석하기" class="nav-link" data-scroll-target="#신뢰구간-해석하기"><span class="header-section-number">8.5.1</span> 신뢰구간 해석하기</a></li>
  <li><a href="#jamovi에서-신뢰구간-계산하기" id="toc-jamovi에서-신뢰구간-계산하기" class="nav-link" data-scroll-target="#jamovi에서-신뢰구간-계산하기"><span class="header-section-number">8.5.2</span> jamovi에서 신뢰구간 계산하기</a></li>
  </ul></li>
  <li><a href="#요약" id="toc-요약" class="nav-link" data-scroll-target="#요약"><span class="header-section-number">8.6</span> 요약</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/kilhwan/jamovi/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header">
<h1 class="title display-7"><span id="sec-Estimating-unknown-quantities-from-a-sample" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">표본으로 미지의 모수 추정하기</span></span></h1>

</header>


<p>지난 장의 시작에서 기술 통계(<em>descriptive statistics</em>)와 추론 통계(<em>inferential statistics</em>)의 중요한 차이점을 강조했습니다. <a href="04-Descriptive-statistics.html" class="quarto-xref"><span>Chapter 4</span></a> 에서 논의한 바와 같이, 기술 통계의 역할은 우리가 <em>알고 있는 것</em>을 간결하게 요약하는 것입니다. 이에 반해, 추론 통계의 목적은 “우리가 알고 있지 않은 것을, 우리가 알고 있는 것으로부터 학습하는 것”입다. 이제 우리는 확률 이론에 대한 기초를 갖추었으므로, 통계적 추론의 문제에 대해 생각해 볼 만 합니다. 우리는 어떤 종류의 정보를 알고자 하는가? 그리고 그것을 어떻게 알 수 있는가? 이러한 질문들이 추론 통계의 핵심을 이루며, 추론 통계는 전통적으로 두 가지 “큰 개념”인 추정(<em>estimation</em>)과 가설 검정(<em>hypothesis testing</em>)으로 나뉜다. 이번 장에서는 이 두 가지 개념 중 첫 번째인 추정 이론(<em>estimation theory</em>)을 소개하는 것이 목표이지만, 추정 이론을 이해하려면 먼저 표본 이론(<em>sampling theory</em>)을 알아야 한다. 따라서, 이 장은 자연스럽게 두 부분으로 나뉜다. 처음 세 개의 절은 표본 이론에 초점을 맞추고 있으며, 마지막 두 개의 절에서는 표본 이론을 활용하여 통계학자들이 추정을 어떻게 생각하는지를 논의할 것이다.</p>
<section id="표본-모집단-및-표본추출" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="표본-모집단-및-표본추출"><span class="header-section-number">8.1</span> 표본, 모집단 및 표본추출</h2>
<p>IV 부의 서두에서 귀납적 추론의 수수께끼를 논의하며, 모든 새로운 사실에 대한 학습은 가정을 필요로 한다는 것을 강조한 바 있다. 이것을 진실이라고 받아들인다면, 우리의 첫 번째 과제는 데이터에 대해 몇 가지 일반적인 가정을 세우는 것이다. 여기서 <strong>표본 이론</strong>(<em>sampling theory</em>)이 등장하게 된다. 확률 이론이 모든 통계 이론을 구축하는 기초라면, 표본 이론은 그 위에 집을 세울 수 있는 틀이라 할 수 있다. 표본 이론은 통계적 추론이 의존하는 가정을 명시하는 데 중요한 역할을 한다. 그리고 통계학자들이 생각하는 방식으로 “추론을 수행하는 것”에 대해 이야기하려면, 우리가 <em>무엇으로부터</em> 추론을 도출하는지(즉, 표본)와 <em>무엇에 대해</em> 추론을 도출하는지(즉, 모집단)를 보다 명확하게 정의할 필요가 있다.</p>
<p>대부분의 연구 상황에서 연구자가 이용할 수 있는 것은 <strong>표본</strong>(<em>sample</em>) 데이터이다. 실험을 수행하여 일정 수의 참가자를 모집할 수도 있고, 여론 조사 기관이 일정 수의 사람들에게 전화를 걸어 투표 의향을 물을 수도 있다. 이러한 방식으로 우리가 확보할 수 있는 데이터 세트는 유한하며 불완전하다. 예를 들어, 실험에 모든 사람을 참여시키는 것은 불가능하며, 여론 조사 기관은 국가의 모든 유권자에게 전화를 걸 시간과 비용을 감당할 수도 없다. <a href="04-Descriptive-statistics.html" class="quarto-xref"><span>Chapter 4</span></a> 에서 기술 통계를 논의할 때, 우리가 관심을 가진 대상은 오직 표본뿐이었다. 우리의 유일한 목표는 해당 표본을 기술하고, 요약하며, 그래프로 나타내는 방법을 찾는 것이었다. 하지만 이제부터는 상황이 달라질 것이다.</p>
<section id="모집단-정의하기" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="모집단-정의하기"><span class="header-section-number">8.1.1</span> 모집단 정의하기</h3>
<p>표본은 구체적인 개념입니다. 데이터 파일을 열어 보면 거기에 표본에서 얻은 데이터가 들어 있습니다. 반면, <strong>모집단</strong>(<em>population</em>)은 더 추상적인 개념입니다. 모집단은 연구자가 결론을 내리고자 하는 모든 가능한 사람들 또는 모든 가능한 관측치를 포함하는 집합을 의미하며, 일반적으로 표본보다 훨씬 더 큽니다. 이상적인 상황에서는 연구자가 연구를 시작할 때 관심 있는 모집단이 무엇인지 명확하게 정의하는 것이 바람직합니다. 연구 설계 및 데이터로 가설을 검증하는 과정은 연구자가 진술하고자 하는 모집단에 따라 달라지기 때문입니다.</p>
<p>어떤 경우에는 관심 있는 모집단을 명확하게 정의하기가 쉽습니다. 예를 들어, 이 장의 서두에서 언급한 “여론 조사 기관” 예시에서 모집단은 연구 시점에 등록된 모든 유권자들로 이루어지며, 이는 수백만 명에 이릅니다. 표본은 그 모집단에 속하는 1000명의 사람들로 구성됩니다. 그러나 대부분의 연구에서는 상황이 훨씬 더 복잡합니다. 일반적인 심리학 실험에서 관심 있는 모집단을 결정하는 것은 다소 까다로울 수 있습니다. 예를 들어, 100명의 학부생을 실험 참가자로 모집하여 실험을 수행한다고 가정해 봅시다. 인지 과학자로서 나는 인간의 정신이 어떻게 작동하는지에 대해 알고자 합니다. 그렇다면 다음 중 무엇이 “모집단”에 해당할까요?</p>
<ul>
<li>애들레이드 대학교의 학부 심리학 학생 전원?</li>
<li>전 세계의 학부 심리학 학생들?</li>
<li>현재 살아 있는 호주인들?</li>
<li>표본과 비슷한 연령대의 호주인들?</li>
<li>현재 살아 있는 모든 사람들?</li>
<li>과거, 현재, 미래의 모든 인간들?</li>
<li>모든 지적 존재들?</li>
</ul>
<p>각 항목은 실제로 정신을 소유한 존재들의 집단을 정의하며, 인지 과학자로서 나에게 모두 흥미로운 대상이 될 수 있습니다. 그러나 이들 중 어떤 집단이 진정한 관심 모집단이어야 하는지는 명확하지 않습니다. 또 다른 예로, IV 부의 서두에서 논의했던 웰즐리-크로커 게임을 고려해 봅시다. 여기에서 표본은 웰즐리가 12번 연속 승리하고 0번 패배한 특정한 게임 결과의 순서를 의미합니다. 그렇다면 모집단은 무엇일까요? 앞의 예와 마찬가지로, 모집단이 무엇인지 명확하지 않습니다.</p>
<ul>
<li>웰즐리와 크로커가 목적지에 도착할 때까지의 모든 게임 결과?</li>
<li>웰즐리와 크로커가 평생 동안 게임을 계속했을 경우의 모든 결과?</li>
<li>웰즐리와 크로커가 영원히 살아남아 세상의 언덕이 다 사라질 때까지 게임을 계속했을 경우의 모든 결과?</li>
<li>무한한 평행 우주를 생성하고, 각 평행 우주의 웰즐리/크로커가 동일한 12개의 언덕에 대해 추측을 했을 경우의 모든 결과?</li>
</ul>
</section>
<section id="단순-무작위-표본" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="단순-무작위-표본"><span class="header-section-number">8.1.2</span> 단순 무작위 표본</h3>
<p>모집단을 어떻게 정의하든 간에 중요한 점은 표본이 모집단의 부분집합이며, 우리가 가진 표본을 이용해 모집단의 특성을 추론하는 것이 목표라는 것입니다. 표본과 모집단 사이의 관계는 표본이 선택된 방식, 즉 <strong>표본추출 방법</strong>(<em>sampling method</em>)에 따라 달라지며, 이 과정이 중요한 이유를 이해하는 것이 필수적입니다.</p>
<p>간단한 예를 들어봅시다. 10개의 칩(chips)이 들어 있는 주머니가 있다고 가정합시다. 각 칩에는 고유한 문자가 인쇄되어 있어 구별할 수 있으며, 칩의 색깔은 검은색과 흰색 두 가지입니다. 이 칩들의 집합이 우리가 관심을 두는 모집단이며, 이는 <a href="#fig-fig8-1" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> 의 왼쪽 그림에 표현되 있습니다. 그림에서 볼 수 있듯이, 검은색 칩이 4개, 흰색 칩이 6개 있지만, 실제로 실험을 수행할 때 주머니 안을 들여다보지 않는 한 이를 알 수는 없습니다. 이제 다음과 같은 “실험”을 진행한다고 가정합시다. 주머니를 흔든 후 눈을 감고 칩 4개를 꺼내되, 꺼낸 칩을 다시 주머니에 넣지 않습니다. 첫 번째로 나온 칩은 <span class="math inline">\(a\)</span>(검은색), 그다음은 <span class="math inline">\(c\)</span>(흰색), 그다음은 <span class="math inline">\(j\)</span>(흰색), 마지막으로 <span class="math inline">\(b\)</span>(검은색)이었습니다. 이후 모든 칩을 다시 주머니에 넣고 같은 실험을 반복할 수 있으며, 이는 <a href="#fig-fig8-1" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> 오른쪽에 표현되어 있습니다. 실험을 반복할 때마다 결과가 다르게 나타날 수 있지만, 과정 자체는 동일합니다. 이렇게 같은 과정이 반복될 때마다 다른 결과가 나올 수 있는 경우를 <em>확률 과정</em>(<em>random process</em>)이라고 합니다.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> 그러나 주머니를 흔든 후 칩을 선택했으므로 모든 칩이 동일한 확률로 선택될 가능성이 높다고 생각할 수 있습니다. 모집단 내 모든 구성원이 동일한 확률로 선택될 수 있는 표본추출 절차를 <strong>단순 무작위 표본추출</strong>(<em>simple random sample</em>)이라고 합니다. 또한, 칩을 꺼낸 후 다시 주머니에 넣지 않았기 때문에 같은 칩을 표본에서 두 번 관찰할 수 없으며, 이러한 경우를 <strong>비복원 표본추출</strong>(<em>sampling without replacement</em>)이라고 합니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-1" class="quarto-float quarto-figure quarto-figure-left anchored" alt="10개의 원이 a에서 j까지 표시된 모집단이 그림으로 표현되어 있다. 화살표는 이 모집단에서 {a, c, j, b}, {i, e, a, f}, {g, c, f, d}의 세 그룹으로 이동하는 것을 나타낸다." data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig8-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:90.0%" alt="10개의 원이 a에서 j까지 표시된 모집단이 그림으로 표현되어 있다. 화살표는 이 모집단에서 {a, c, j, b}, {i, e, a, f}, {g, c, f, d}의 세 그룹으로 이동하는 것을 나타낸다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1. 유한 모집단에서의 비복원 단순 무작위 표본추출
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-2" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="a에서 j까지 표시된 10개의 항목으로 구성된 모집단에서 비복원 표본추출이 이루어지는 과정을 그림으로 나타냈다. 각 샘플 세트는 네 개의 항목으로 이루어지며, 예시로 {a, b, g, h}, {g, b, h, a}, {a, h, b, g}가 포함된다. 검은색 원은 선택된 항목을, 흰색 원은 선택되지 않은 항목을 나타낸다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig8-2.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:90.0%" data-fig-pos="H" alt="a에서 j까지 표시된 10개의 항목으로 구성된 모집단에서 비복원 표본추출이 이루어지는 과정을 그림으로 나타냈다. 각 샘플 세트는 네 개의 항목으로 이루어지며, 예시로 {a, b, g, h}, {g, b, h, a}, {a, h, b, g}가 포함된다. 검은색 원은 선택된 항목을, 흰색 원은 선택되지 않은 항목을 나타낸다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2. 유한 모집단에서의 편향된 비복원 표본추출
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-3" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="모집단(10개의 검은색 및 흰색 원으로 이루어진 a부터 j까지의 항목)이 왼쪽에 나타나 있다. 세 개의 표본(각각 4개의 원으로 구성됨)이 오른쪽에 나타나 있으며, 모집단에서 화살표가 이들 표본으로 연결되어 있다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig8-3.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:90.0%" data-fig-pos="H" alt="모집단(10개의 검은색 및 흰색 원으로 이루어진 a부터 j까지의 항목)이 왼쪽에 나타나 있다. 세 개의 표본(각각 4개의 원으로 구성됨)이 오른쪽에 나타나 있으며, 모집단에서 화살표가 이들 표본으로 연결되어 있다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3. 유한 모집단에서의 단순 무작위 복원 표본추출
</figcaption>
</figure>
</div>
</div>
</div>
<p>표본추출 절차의 중요성을 이해하기 위해 다른 실험 방식을 고려해 봅시다. 만약 다섯 살짜리 아이가 주머니를 열고 검은색 칩 4개를 골라내며, 꺼낸 칩을 다시 넣지 않는 방식으로 진행했다면 어떻게 될까요? 이러한 편향된 표본추출 방식은 <a href="#fig-fig8-2" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> 에 표현되어 있습니다. 이제 4개의 검은색 칩이 선택되고 흰색 칩이 하나도 선택되지 않았다는 사건이 갖는 증거로서의 가치를 생각해 봅시다. 이는 표본추출 방식에 따라 다르지 않을까요? 만약 특정 색깔의 칩만 선택하도록 편향된 표본추출한 방식이라면, 검은색 칩만 포함된 표본이 모집단에 대해 제공하는 정보는 매우 제한적일 것입니다. 이러한 이유로 통계학자들은 데이터가 단순 무작위 표본일 때를 선호합니다. 이렇게 하면 데이터 분석이 <em>훨씬</em> 쉬워지기 때문입니다.</p>
<p>또 다른 표본추출 방법도 고려할 가치가 있습니다. 이번에는 눈을 감고 주머니를 흔든 후 칩을 하나 꺼냅니다. 그러나 이번에는 관측값을 기록한 후 칩을 다시 주머니에 넣고 같은 과정을 반복하여 4개의 칩을 선택합니다. 이처럼 선택한 항목을 다시 모집단에 포함시키는 방식을 <strong>복원 표본추출</strong>(<em>sampling with replacement</em>)이라고 합니다. 이 방식에서는 동일한 모집단 항목이 여러 번 관찰될 가능성이 있으며, 이는 <a href="#fig-fig8-3" class="quarto-xref">Figure&nbsp;<span>8.3</span></a> 에서 설명되어 있습니다.</p>
<p>내 경험에 따르면 대부분의 심리학 실험은 비복원 표본추출 방식을 따릅니다. 왜냐하면 같은 사람이 두 번 실험에 참여하는 것이 허용되지 않기 때문입니다. 그러나 대부분의 통계 이론은 <strong>복원 표본추출</strong>을 가정하여 개발됩니다. 하지만 현실에서는 이 차이가 거의 문제가 되지 않습니다. 모집단이 충분히 클 경우(예: 10개 이상의 개체가 존재할 경우)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> 복원 표본추출과 비복원 표본추출 간의 차이는 무시할 수 있을 정도로 작기 때문입니다. 반면, 단순 무작위 표본과 편향된 표본 간의 차이는 간과하기 어려운 차이를 가집니다.</p>
</section>
<section id="대부분의-표본은-단순-무작위-표본이-아니다" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="대부분의-표본은-단순-무작위-표본이-아니다"><span class="header-section-number">8.1.3</span> 대부분의 표본은 단순 무작위 표본이 아니다</h3>
<p>위에서 제시한 가능한 모집단 목록을 보면 알 수 있듯이, 우리가 관심을 갖는 대부분의 모집단에서 단순 무작위 표본을 얻는 것은 거의 불가능합니다. 내가 실험을 진행할 때, 참가자가 애들레이드 대학교의 학부 심리학 학생들 중에서 무작위로 표본추출되었다면, 그것만으로도 작은 기적이라고 생각할 것입니다. 이는 내가 일반화하고 싶은 모집단 중에서 가장 좁은 범주임에도 그렇습니다. 다른 유형의 표본추출 방법에 대한 자세한 논의는 이 책의 범위를 벗어나지만, 대략적인 개념을 제공하기 위해 몇 가지 중요한 방법을 소개하겠습니다.</p>
<ul>
<li><p><strong>층화 표본추출(stratified sampling)</strong>: 모집단이 여러 개의 하위 모집단(층)으로 나뉘어 있거나 나눌 수 있다고 가정해 봅시다. 예를 들어, 여러 다른 지역에서 연구를 진행할 수도 있습니다. 모집단 전체에서 무작위로 표본을 추출하는 대신, 각 층에서 별도로 무작위 표본을 수집하는 방식을 사용할 수도 있습니다. 층화 표본추출은 모집단이 이미 명확한 층으로 나누어져 있을 경우 단순 무작위 표본추출보다 더 쉽고, 특히 희귀한 하위 모집단을 포함하고 있을 때 더 효율적일 수 있습니다. 예를 들어, 조현병을 연구할 때 모집단을 두 개의 층(조현병 환자와 비(非)조현병 환자)으로 나누고, 각 그룹에서 동일한 수의 사람을 표본으로 추출하는 것이 훨씬 더 나은 방법일 것입니다. 무작위로 사람을 선택하면 조현병 환자가 표본에 거의 포함되지 않아 연구가 무의미해질 수도 있습니다. 이러한 특정한 층화 표본추출 방식을 <strong>과표집(oversampling)</strong>이라고 하며, 희귀한 그룹을 의도적으로 더 많이 포함하도록 하는 기법입니다.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p></li>
<li><p><strong>눈덩이 표본추출(snowball sampling)</strong>: “숨겨진” 또는 접근하기 어려운 모집단에서 표본을 추출할 때 유용한 기법이며, 특히 사회과학에서 흔히 사용됩니다. 예를 들어, 연구자가 트랜스젠더 집단을 대상으로 여론 조사를 하고 싶다고 가정해 봅시다. 연구팀이 처음에는 소수의 트랜스젠더 참여자에 대한 연락처만 가지고 있을 수 있습니다. 따라서 연구는 우선 이들에게 설문에 참여해 달라고 요청하는 것으로 시작됩니다(1단계). 설문이 끝난 후, 연구자는 이들에게 추가로 참여할 만한 다른 사람들의 연락처를 제공해 달라고 요청합니다. 이렇게 확보된 새로운 연락처를 대상으로 2단계 조사가 진행됩니다. 이러한 과정이 반복되면서 연구자는 충분한 데이터를 확보하게 됩니다. 눈덩이 표본추출의 가장 큰 장점은 일반적으로 데이터를 확보하기 어려운 상황에서도 표본을 얻을 수 있다는 점입니다. 그러나 통계적으로는 표본이 매우 비무작위적이며, 그 비무작위성이 어떻게 작용하는지 파악하기 어렵다는 단점이 있습니다. 또한 현실적인 문제도 있습니다. 모집단이 “숨겨진” 이유가 있는 경우가 많기 때문에, 이 방법을 잘못 사용할 경우 비윤리적인 결과를 초래할 수 있습니다. 여기서 트랜스젠더 집단을 예로 든 이유도 이와 관련이 있습니다. 연구자가 조심하지 않으면, 원치 않는 사람을 아웃팅(outing)하게 될 수도 있으며(이는 매우 심각한 실수입니다), 그런 실수를 하지 않더라도 사람들의 사회적 네트워크를 연구 목적으로 이용하는 것이 사생활 침해로 느껴질 수 있습니다. 무엇보다, 연구자가 사람들에게 연락을 취하기 전에 미리 동의를 얻는 것이 어렵다는 점도 문제입니다. 때로는 단순히 “우리가 당신을 연구하고 싶다”는 의도를 밝히는 것만으로도 상처를 줄 수 있습니다. 사회적 네트워크는 복잡한 구조를 가지고 있으며, 사회적 네트워크로 데이터를 수집할 수 있다고 해서 그렇게 하는 것이 좋은 것은 아닐 수 있다는 것을 기억해야 합니다.</p></li>
<li><p><strong>편의 표본추출(convenience sampling)</strong>: 말 그대로 연구자에게 편리한 방식으로 표본을 선택하는 방법이며, 모집단에서 무작위로 선택하는 것은 아닙니다. 눈덩이 표본추출도 편의 표본추출의 한 형태이지만, 이 외에도 다양한 방식이 존재합니다. 심리학 연구에서 흔히 볼 수 있는 예로, 학부 심리학 학생들을 대상으로 한 연구를 들 수 있습니다. 이러한 표본은 일반적으로 두 가지 측면에서 비무작위적입니다. 첫째, 학부 심리학 학생들을 대상으로 한다는 것 자체가 특정 하위 모집단에 국한된다는 점입니다. 둘째, 학생들이 어떤 연구에 참여할지를 직접 선택하는 경우가 많기 때문에, 이는 심리학 학생들 전체에서 무작위로 선택된 하위 집단이 아니라 자발적으로 참여한 일부 집단이라는 점에서 더욱 비무작위적입니다. 현실적으로 보면, 대부분의 연구는 어느 정도 편의 표본추출에 의존합니다. 이는 연구의 중요한 한계가 될 수도 있지만, 반드시 그렇지만은 않습니다.</p></li>
</ul>
</section>
<section id="단순-무작위-표본이-아니면-얼마나-문제가-될까" class="level3" data-number="8.1.4">
<h3 data-number="8.1.4" class="anchored" data-anchor-id="단순-무작위-표본이-아니면-얼마나-문제가-될까"><span class="header-section-number">8.1.4</span> 단순 무작위 표본이 아니면 얼마나 문제가 될까?</h3>
<p>현실에서 데이터를 수집할 때는 대부분 단순 무작위 표본을 사용하지 않습니다. 그렇다면 이것이 문제가 될까요? 조금만 생각해 보면, 데이터가 단순 무작위 표본이 아닐 경우 문제가 될 수 있다는 점이 명확해집니다. <a href="#fig-fig8-1" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> 과 <a href="#fig-fig8-2" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> 의 차이를 생각해 보면 됩니다. 하지만 걱정할 만큼 나쁜 상황은 아닙니다. 일부 유형의 편향된 표본은 전혀 문제가 되지 않습니다. 예를 들어, 층화 표본추출 기법을 사용할 경우 연구자가 의도적으로 편향을 만들었으며, 이는 종종 연구의 효과를 <em>높이기</em> 위한 것입니다. 또한, 이러한 경우에는 연구자가 만든 편향을 보정할 수 있는 통계적 기법도 존재합니다(이 책에서는 다루지 않지만!). 따라서 이러한 상황에서는 문제가 되지 않습니다.</p>
<p>보다 일반적으로 보았을 때, 무작위 표본추출은 수단이지 목적이 아니라는 점을 기억하는 것이 중요합니다. 편의 표본에 의존했다고 가정해 봅시다. 그렇다면 표본이 편향되었을 가능성이 큽니다. 하지만 표본추출 과정에서 편향이 발생했다고 해서 반드시 문제가 되는 것은 아닙니다. 문제가 되는 경우는 그 편향이 잘못된 결론을 내리게 만드는 경우뿐입니다. 이런 관점에서 본다면, 표본이 <em>모든</em> 면에서 무작위적일 필요는 없으며, 연구에서 관심을 두고 있는 심리학적 현상과 관련하여 무작위적이면 충분합니다.</p>
<p>예를 들어, 내가 작업 기억 용량(working memory capacity)에 대한 연구를 진행한다고 가정해 봅시다. 연구 1에서는 현재 살아 있는 모든 인간을 대상으로 무작위 표본을 추출할 수 있는 능력을 갖고 있지만, 한 가지 예외가 있습니다. 월요일에 태어난 사람만 표본으로 선택할 수 있습니다. 연구 2에서는 호주 인구에서 무작위로 표본을 추출할 수 있습니다. 나는 연구 결과를 전 세계 모든 인간에게 일반화하고 싶습니다. 그렇다면 어느 연구가 더 나을까요? 당연히 연구 1입니다. 왜일까? “월요일에 태어났다”는 것이 작업 기억 용량과 관련이 있을 이유가 전혀 없기 때문입니다. 반면, “호주에서 태어났다”는 것은 다를 수 있습니다. 호주는 부유한 산업국이며, 매우 잘 발달된 교육 시스템을 갖추고 있습니다. 이 시스템에서 성장한 사람들은 작업 기억 용량을 측정하는 테스트를 설계한 사람들과 훨씬 더 유사한 삶의 경험을 공유했을 가능성이 높습니다. 이러한 공통된 경험은 테스트를 어떻게 수행해야 하는지에 대한 유사한 신념을 형성할 수도 있고, 심리학 실험이 어떻게 진행되는지에 대한 공통된 가정을 만들 수도 있습니다. 이런 요소들은 실제로 중요한 영향을 미칠 수 있습니다. 예를 들어, “시험 방식”이 호주 참가자들에게 보다 추상적인 시험 자료에 집중하는 법을 가르쳤을 수도 있습니다. 반면, 유사한 환경에서 성장하지 않은 사람들은 이러한 방식에 익숙하지 않을 수 있습니다. 따라서 이런 편향된 표본이 작업 기억 용량에 대한 잘못된 판단을 하게 만들 수도 있습니다.</p>
<p>이 논의에서 두 가지 중요한 점을 짚어볼 수 있습니다. 첫째, 연구를 설계할 때 어떤 모집단을 연구 대상으로 삼을 것인지 신중하게 생각하고, 그 모집단에 적합한 방식으로 표본을 추출하려고 노력해야 합니다. 현실적으로는 대부분 “편의 표본”을 사용할 수밖에 없는 경우가 많습니다(예: 심리학 교수들이 심리학 학생들을 대상으로 연구를 수행하는 이유는 비용이 가장 적게 들기 때문이며, 학계의 예산은 풍족하지 않습니다). 하지만 그렇다고 해도, 이러한 방법이 초래할 위험이 무엇인지에 대해 고민하는 것이 필요합니다. 둘째, 다른 연구자의 연구를 비판할 때, 단순히 그들이 편의 표본을 사용했다고 해서 비판하는 것은 적절하지 않습니다. 만약 연구 결과가 왜곡되었을 가능성이 있다고 주장하려면, 최소한 그 편향이 결과에 어떤 영향을 미쳤을지에 대한 구체적인 이론을 제시하는 것이 예의일 것입니다.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="작업 기억이란">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
작업 기억이란
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>작업 기억(working memory)</strong>는 정보를 짧은 시간 동안 <strong>일시적으로 저장하고 조작하는 능력</strong>을 말합니다. 이는 우리가 <strong>복잡한 인지 작업</strong>을 수행할 때 필수적인 역할을 합니다. 예를 들어, <strong>문제 해결, 의사 결정, 언어 이해, 계산</strong> 등의 과정에서 작업 기억이 활발하게 사용됩니다.</p>
<p><strong>작업 기억의 주요 특징</strong>은 다음과 같습니다.</p>
<ol type="1">
<li><strong>일시적 저장</strong>: 정보를 짧은 시간 동안만 유지합니다. (몇 초에서 수십 초 정도)</li>
<li><strong>정보 조작</strong>: 단순히 저장하는 것뿐만 아니라 그 정보를 <strong>활용하거나 변형</strong>할 수 있습니다.</li>
<li><strong>제한된 용량</strong>: 한 번에 처리할 수 있는 정보의 양이 제한되어 있습니다. (보통 7±2 개의 항목이라고 알려짐)</li>
</ol>
<p><strong>작업 기억의 구성 요소</strong>에 대한 Baddeley &amp; Hitch 자신의 모형에서 다음과 같이 설명합니다.</p>
<ol type="1">
<li><strong>중앙 집행기(Central Executive)</strong>:
<ul>
<li>작업 기억의 <strong>컨트롤 타워</strong> 역할을 합니다.<br>
</li>
<li>주의 집중, 정보 전환, 억제 등을 관리합니다.</li>
</ul></li>
<li><strong>음운 루프(Phonological Loop)</strong>:
<ul>
<li><strong>언어적 정보</strong>(단어, 숫자 등)를 처리하고 유지합니다.<br>
</li>
<li>예: 전화번호를 머릿속으로 반복하며 기억하기.</li>
</ul></li>
<li><strong>시공간 스케치패드(Visuospatial Sketchpad)</strong>:
<ul>
<li><strong>시각적 및 공간적 정보</strong>를 처리합니다.<br>
</li>
<li>예: 지도를 떠올리며 길 찾기.</li>
</ul></li>
<li><strong>에피소드 버퍼(Episodic Buffer)</strong>:
<ul>
<li>여러 종류의 정보를 통합하고 <strong>장기 기억과 연결</strong>합니다.</li>
</ul></li>
</ol>
<p>작업 기억이 사용되는 작업의 예는 다음과 같습니다.</p>
<ul>
<li><strong>암산하기</strong>: 37 + 48을 머릿속으로 계산할 때, 숫자들을 기억하고 더하는 과정을 조작합니다.<br>
</li>
<li><strong>지시 따르기</strong>: “왼쪽으로 가서 두 번째 문을 열어”라는 지시를 듣고 행동하기.<br>
</li>
<li><strong>문장 이해하기</strong>: 긴 문장을 읽으면서 앞 문장의 내용을 기억하고 연결하기.</li>
</ul>
<p><strong>작업 기억</strong>과 <strong>단기 기억</strong>의 차이는 다음과 같습니다.</p>
<ul>
<li><strong>단기 기억</strong>: 정보를 단순히 <strong>잠시 저장</strong>하는 것에 초점.<br>
</li>
<li><strong>작업 기억</strong>: 저장뿐만 아니라 정보를 <strong>활발히 조작</strong>하는 것이 특징.</li>
</ul>
<p>이해하기 쉽게 말하면, <strong>단기 기억은 정보를 “메모”하는 종이 쪽지</strong>이고, <strong>작업 기억은 그 쪽지를 보면서 “계산하거나 생각하는 작업 공간”</strong>이라고 볼 수 있습니다.</p>
</div>
</div>
</section>
<section id="모집단-모수와-표본-통계량" class="level3" data-number="8.1.5">
<h3 data-number="8.1.5" class="anchored" data-anchor-id="모집단-모수와-표본-통계량"><span class="header-section-number">8.1.5</span> 모집단 모수와 표본 통계량</h3>
<p>이제, 무작위 표본을 얻는 과정에서 발생하는 까다로운 방법론적 문제를 잠시 제쳐두고, 약간 다른 문제를 고려해 봅시다. 지금까지 우리는 과학자가 모집단을 바라보는 방식에 대해 이야기했습니다. 심리학자에게 모집단은 사람들의 집단일 수 있고, 생태학자에게 모집단은 곰들의 집단일 수 있습니다. 대부분의 경우, 과학자들이 관심을 가지는 모집단은 실제 세계에 존재하는 구체적인 것들입니다. 그러나 통계학자들은 다소 독특한 사고방식을 가집니다. 한편으로는 과학자들처럼 현실 세계의 데이터와 과학에 관심이 있지만, 다른 한편으로는 수학자들처럼 순수한 추상적 개념을 다루기도 합니다. 그 결과, 통계 이론에서는 모집단을 다소 추상적으로 정의하는 경향이 있습니다. 심리학 연구자들이 추상적인 이론적 개념을 구체적인 측정값으로 조작적으로 정의하듯이(<a href="02-A-brief-introduction-to-research-design.html#sec-Introduction-to-psychological-measurement" class="quarto-xref"><span>Section 2.1</span></a>), 통계학자들도 모집단 개념을 자신들이 다룰 수 있는 수학적 객체로 조작적으로 정의합니다. 여러분은 이 조작적 객체를 이미 <a href="07-Introduction-to-probability.html" class="quarto-xref"><span>Chapter 7</span></a> 에서 보았습니다. 바로 <strong>확률분포(probability distributions)</strong>입니다.</p>
<p>개념은 비교적 간단합니다. 예를 들어, 우리가 IQ 점수에 대해 논의한다고 가정해 봅시다. 심리학자에게 모집단은 IQ 점수를 가진 실제 인간 집단입니다. 그러나 통계학자는 이를 보다 단순하게 만들어 <a href="#fig-fig8-4" class="quarto-xref">Figure&nbsp;<span>8.4</span></a> (a)에서 나타난 확률분포로 조작적으로 정의합니다. IQ 테스트는 평균 IQ가 100이고, 표준 편차가 15이며, IQ 점수 분포가 정규 분포를 따르도록 설계됩니다. 이러한 값들을 <strong>모집단 모수(population parameters)</strong>라고 하며, 이는 모집단 전체의 특성을 나타냅니다. 즉, 모집단의 평균 ()는 100이고, 모집단의 표준 편차 ()는 15라고 말할 수 있습니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-4" class="quarto-float quarto-figure quarto-figure-left anchored" alt="이 이미지는 IQ 점수에 대한 세 개의 그래프를 포함한다. 왼쪽 그래프는 확률 밀도 곡선, 가운데 그래프는 빈도를 나타내는 히스토그램, 오른쪽 그래프는 더 높은 빈도의 히스토그램이다. 모든 그래프의 x축에는 IQ 점수가 표시되어 있다." data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-4-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" alt="이 이미지는 IQ 점수에 대한 세 개의 그래프를 포함한다. 왼쪽 그래프는 확률 밀도 곡선, 가운데 그래프는 빈도를 나타내는 히스토그램, 오른쪽 그래프는 더 높은 빈도의 히스토그램이다. 모든 그래프의 x축에는 IQ 점수가 표시되어 있다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4. IQ 점수의 모집단 분포(패널 (a))와 무작위로 추출한 두 개의 표본. 패널 (b)는 100개의 표본을, 패널 (c)는 10,000개의 표본을 포함하고 있다.
</figcaption>
</figure>
</div>
</div>
</div>
<p>이제, 실험을 수행한다고 가정해 봅니다. 나는 무작위로 100명을 선택하여 IQ 테스트를 실시하고, 이를 통해 모집단에서 단순 무작위 표본을 얻습니다. 내 표본은 다음과 같은 숫자들로 구성될 것입니다.</p>
<blockquote class="blockquote">
<p>106 101 98 80 74 … 107 72 100</p>
</blockquote>
<p>각각의 IQ 점수는 평균이 100이고 표준 편차가 15인 정규 분포에서 추출된 값입니다. 따라서 표본의 히스토그램을 그려보면 <a href="#fig-fig8-4" class="quarto-xref">Figure&nbsp;<span>8.4</span></a> (b)와 같은 모양이 됩니다. 보시다시피, 히스토그램의 형태는 모집단 분포(<a href="#fig-fig8-4" class="quarto-xref">Figure&nbsp;<span>8.4</span></a> (a) 참조)와 대체로 유사하지만, 여전히 매우 조잡한 근사값에 불과합니다. 표본의 평균을 계산하면 모집단 평균인 100에 가까운 값을 얻을 수 있지만, 정확히 동일하지는 않습니다. 이 경우, 내 표본에 포함된 사람들의 평균 IQ는 98.5이고, 표준 편차는 15.9로 나타났습니다. 이러한 값들을 <strong>표본 통계량(sample statistics)</strong>이라고 하며, 이는 내 데이터 집합의 특성을 나타냅니다. 표본 통계량은 모집단의 실제 값과 유사하지만 동일하지는 않습니다. 일반적으로, 표본 통계량은 우리가 데이터에서 직접 계산할 수 있는 값이며, 모집단 모수는 우리가 알아내고자 하는 대상입니다.</p>
<p>이 장의 뒷부분에서, [모집단 모수 추정]을 위해 표본 통계량을 사용하는 방법과 <a href="#sec-Estimating-a-confidence-interval">신뢰구간 추정</a>에 대해 논의할 것입니다. 하지만 그 전에 표본 이론(sampling theory)에서 더 알아야 할 몇 가지 개념이 남아 있습니다.</p>
</section>
</section>
<section id="대수의-법칙" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="대수의-법칙"><span class="header-section-number">8.2</span> 대수의 법칙</h2>
<p>이전 절에서 표본 크기가 <span class="math inline">\(N = 100\)</span>인 가상의 IQ 실험 결과를 보여주었습니다. 실제 모집단 평균이 100이고 표본 평균이 98.5인 것을 보면, 이는 비교적 정확한 추정치임을 알 수 있습니다. 많은 과학 연구에서 이 정도의 정밀도는 충분히 받아들일 수 있지만, 어떤 경우에는 훨씬 더 정밀한 결과가 필요합니다. 그렇다면 표본 통계량을 모집단 모수에 더 가깝게 만들려면 어떻게 해야 할까요? 가장 명백한 해결책은 더 많은 데이터를 수집하는 것입니다. 이제 10,000명의 IQ를 측정하는 훨씬 더 큰 실험을 수행했다고 가정해 봅시다. 우리는 jamovi를 사용하여 이 실험의 결과를 시뮬레이션할 수 있습니다. <code>IQsim.omv</code> 파일은 jamovi 데이터 파일로, 평균이 100이고 표준 편차가 15인 모집단에서 정규 분포를 따르는 10,000개의 난수를 생성한 것입니다. 이 작업은 jamovi의 ‘= NORM(100,15)’ 함수를 사용하여 새로운 변수를 계산함으로써 수행되었습니다. <a href="#fig-fig8-5" class="quarto-xref">Figure&nbsp;<span>8.5</span></a> 의 히스토그램과 밀도 그래프를 보면, 더 큰 표본이 모집단의 실제 분포를 더 잘 반영한다는 것을 확인할 수 있습니다. 이는 표본 통계량에도 반영됩니다. 더 큰 표본에서 얻은 평균 IQ는 99.68, 표준 편차는 14.90으로, 이제 모집단의 실제 값과 매우 가까워졌습니다.</p>
<div class="cell enlarge-image" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-5" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="h!" data-fig-align="left" alt="jamovi 스크린샷이 표시됩니다. 변수 조작 및 데이터 분석을 위한 메뉴가 포함되어 있습니다. IQsim이라는 계산된 변수가 공식과 함께 나타나며, 숫자로 구성된 IQsim 값 목록과 기술 통계를 포함한 히스토그램이 오른쪽에 표시됩니다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/kor/fig8-5.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="h!" alt="jamovi 스크린샷이 표시됩니다. 변수 조작 및 데이터 분석을 위한 메뉴가 포함되어 있습니다. IQsim이라는 계산된 변수가 공식과 함께 나타나며, 숫자로 구성된 IQsim 값 목록과 기술 통계를 포함한 히스토그램이 오른쪽에 표시됩니다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5. jamovi를 사용하여 정규 분포에서 추출한 무작위 표본
</figcaption>
</figure>
</div>
</div>
</div>
<p>이 말을 하는 것이 조금 부질없게 느껴지지만, 여러분이 반드시 기억해야 할 것은 표본 크기가 클수록 더 좋은 정보를 얻을 수 있다는 점입니다. 사실 이 점은 너무나도 명백해서 굳이 언급할 필요도 없어 보입니다. 실제로 확률론의 창시자 중 한 명인 야코프 베르누이는 1713년에 이 개념을 공식화하면서 다소 거만한 태도를 보였습니다. 그는 다음과 같이 설명했습니다.</p>
<blockquote class="blockquote">
<p><em>“가장 어리석은 사람조차도 어떤 본능적인 직관에 의해, 그리고 별다른 가르침 없이도(이는 주목할 만한 점이다), 더 많은 관찰이 이루어질수록 목표에서 벗어날 위험이 줄어든다는 것을 확신하게 된다.”</em> <span class="citation" data-cites="Stigler1986">(<a href="References.html#ref-Stigler1986" role="doc-biblioref">Stigler, 1986, p. 65</a>)</span></p>
</blockquote>
<p>이 문장은 다소 무례하게 들릴 수도 있고(게다가 성차별적인 느낌도 있습니다), 하지만 그의 핵심 주장 자체는 맞습니다. 우리는 본능적으로 더 많은 데이터가 더 나은 결과를 가져온다는 사실을 이해하고 있습니다. 그렇다면, 왜 그런 걸까요? 놀랍지 않게도, 우리가 공유하는 이 직관은 정확하며, 통계학자들은 이를 <strong>대수의 법칙(law of large numbers)</strong>이라고 부릅니다. 대수의 법칙은 여러 가지 표본 통계량에 적용되는 수학적 법칙이지만, 가장 쉽게 이해할 수 있는 방식은 이를 평균에 대한 법칙으로 보는 것입니다. 표본 평균은 평균을 계산하는 과정(즉, 여러 값의 평균을 구하는 것)에서 비롯되는 통계량이므로, 이를 통해 대수의 법칙을 살펴보겠습니다. 대수의 법칙이 표본 평균에 적용될 때, 이 법칙은 다음과 같이 말합니다. 표본 크기가 커질수록 표본 평균은 모집단 평균에 점점 더 가까워진다는 것입니다. 보다 정확히 표현하면, 표본 크기가 무한대로 증가할 때(<span class="math inline">\(N \longrightarrow \infty\)</span>), 표본 평균은 모집단 평균에 수렴합니다(<span class="math inline">\(\bar{X} \longrightarrow \mu\)</span>)<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>대수의 법칙이 참이라는 것을 증명할 생각은 없지만, 이는 통계 이론에서 가장 중요한 도구 중 하나입니다. 대수의 법칙은 우리가 점점 더 많은 데이터를 수집하면 결국 진실에 가까워질 것이라는 믿음을 정당화하는 근거가 됩니다. 어떤 특정한 데이터 집합에서 계산된 표본 통계량이 완벽히 정확할 가능성은 낮지만, 대수의 법칙에 따르면 더 많은 데이터를 수집할수록 표본 통계량은 점점 모집단 모수에 가까워지게 됩니다.</p>
</section>
<section id="표본-분포와-중심극한정리" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="표본-분포와-중심극한정리"><span class="header-section-number">8.3</span> 표본 분포와 중심극한정리</h2>
<p>대수의 법칙은 매우 강력한 도구이지만, 우리의 모든 질문에 답해줄 수는 없습니다. 이 법칙이 제공하는 것은 기본적으로 “장기적인 보장”일 뿐입니다. 즉, 우리가 무한한 양의 데이터를 수집할 수 있다고 가정하면, 대수의 법칙은 우리가 구한 표본 통계량이 정확할 것이라고 보장합니다. 하지만 경제학자 존 메이너드 케인스가 유명하게 지적했듯이, 장기적인 보장은 현실 세계에서 그다지 유용하지 않습니다.</p>
<blockquote class="blockquote">
<p><em>“[장기적인 관점은] 현재의 문제를 해결하는 데 있어 잘못된 길잡이가 될 수 있습니다. 장기적으로 보면 우리는 모두 죽습니다. 경제학자들이 폭풍이 지나고 바다가 다시 평온해질 것이라고 말하는 것은 격동의 시기에는 아무런 도움도 되지 않습니다.”</em> <span class="citation" data-cites="Keynes1923">(<a href="References.html#ref-Keynes1923" role="doc-biblioref">Keynes, 1923, p. 80</a>)</span></p>
</blockquote>
<p>경제학에서 그렇듯이, 심리학과 통계학에서도 마찬가지입니다. 표본 평균을 계산할 때 결국에는 올바른 답을 얻게 된다는 것만으로는 충분하지 않습니다. 표본 크기가 <span class="math inline">\(N = 100\)</span>인 실제 데이터 집합을 다루는 상황에서, 무한히 큰 데이터 집합이 모집단 평균의 정확한 값을 알려줄 것이라는 사실은 아무런 위안이 되지 않습니다. 현실에서는, 더 작은 표본에서 표본 평균이 어떤 행태를 보이는지를 이해하는 것이 필수적입니다.</p>
<section id="sec-Sampling-distribution-of-the-mean" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="sec-Sampling-distribution-of-the-mean"><span class="header-section-number">8.3.1</span> 평균의 표본 분포</h3>
<p>이 점을 염두에 두고, 이제 표본 크기가 10,000인 연구를 고려하는 대신 훨씬 더 작은 실험을 생각해 보겠습니다. 이번에는 <span class="math inline">\(N = 5\)</span>명의 사람을 표본으로 선정하여 그들의 IQ 점수를 측정합니다. 이전과 마찬가지로 jamovi의 ‘= NORM(100,15)’ 함수를 사용하여 이 실험을 시뮬레이션할 수 있지만, 이번에는 10,000명이 아니라 단 5명의 참가자만 필요합니다. jamovi가 생성한 다섯 개의 숫자는 다음과 같습니다.</p>
<blockquote class="blockquote">
<p>90 82 94 99 110</p>
</blockquote>
<p>이 표본에서의 평균 IQ는 정확히 95입니다. 예상할 수 있듯이, 이는 이전 실험보다 훨씬 덜 정확한 결과입니다. 이제 내가 이 실험을 <strong>반복</strong>하기로 결정했다고 가정해 봅시다. 즉, 가능한 한 동일한 절차를 다시 수행하고, 무작위로 새로운 5명을 선정하여 그들의 IQ를 측정하는 것입니다. jamovi를 사용하면 이 과정을 다시 시뮬레이션할 수 있으며, 다음과 같은 다섯 개의 숫자가 생성됩니다.</p>
<blockquote class="blockquote">
<p>78 88 111 111 117</p>
</blockquote>
<p>이번 표본에서의 평균 IQ는 101입니다. 실험을 10번 반복하면 <a href="#tbl-tab8-1" class="quarto-xref">Table&nbsp;<span>8.1</span></a> 에서 볼 수 있는 결과를 얻게 되며, 각 반복에서 표본 평균이 달라진다는 것을 확인할 수 있습니다.</p>
<div class="cell" data-layout-align="left">
<div id="tbl-tab8-1" class="cell quarto-float quarto-figure quarto-figure-left anchored" data-layout-align="left">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tab8-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.1. 각 표본 크기가 <span class="math inline">\(( N = 5 )\)</span>인 IQ 실험의 10번 반복 결과
</figcaption>
<div aria-describedby="tbl-tab8-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:tbl-tab8-1">
<colgroup><col><col><col><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: bold;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">사람 1</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">사람 2</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">사람 3</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">사람 4</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">사람 5</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: bold;">표본평균</th></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 1</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">90</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">82</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">94</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">99</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">110</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">95.0</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 2</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">78</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">88</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">111</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">111</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">117</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">101.0</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 3</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">111</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">122</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">91</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">98</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">86</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">101.6</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 4</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">98</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">96</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">119</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">99</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">107</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">103.8</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 5</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">105</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">113</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">103</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">103</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">98</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">104.4</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 6</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">81</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">89</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">93</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">85</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">114</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">92.4</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 7</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">100</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">93</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">108</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">98</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">133</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">106.4</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 8</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">107</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">100</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">105</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">117</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">85</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">102.8</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 9</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">86</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">119</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">108</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">73</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">116</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">100.4</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">반복 10</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">95</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">126</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">112</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">120</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">76</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">105.8</td></tr>
</tbody></table>

</div>
</div>
</figure>
</div>
</div>
<p>이제 이 방식대로 계속해서 “5명의 IQ 점수” 실험을 반복한다고 가정해 봅시다. 매번 실험을 반복할 때마다 표본 평균을 기록합니다. 시간이 지나면서 새로운 데이터 집합이 축적될 것입니다. 이 데이터 집합에서는 각 실험이 단일 데이터 포인트를 생성합니다. 내 데이터 집합에서 처음 10개의 관측치는 <a href="#tbl-tab8-1" class="quarto-xref">Table&nbsp;<span>8.1</span></a> 에 나열된 표본 평균이며, 다음과 같이 시작됩니다.</p>
<blockquote class="blockquote">
<p>95.0 101.0 101.6 103.8 104.4 …</p>
</blockquote>
<p>이 과정을 10,000번 반복한 후 히스토그램을 그려보면 어떻게 될까요? 실제로 그렇게 해보았으며, 그 결과는 <a href="#fig-fig8-6" class="quarto-xref">Figure&nbsp;<span>8.6</span></a> 에서 확인할 수 있습니다. 이 그림이 보여주듯이, 5개의 IQ 점수를 평균 내면 보통 90에서 110 사이의 값이 나옵니다. 하지만 더 중요한 점은, 실험을 여러 번 반복하면 <strong>표본 평균의 분포</strong>가 형성된다는 것입니다! (<a href="#tbl-tab8-1" class="quarto-xref">Table&nbsp;<span>8.1</span></a>). 통계학에서 이 분포를 <strong>평균의 표본 분포</strong>라고 부릅니다.</p>
<p>표본 분포는 통계학에서 또 하나의 중요한 이론적 개념이며, 작은 표본의 특성을 이해하는 데 필수적입니다. 예를 들어, 처음 수행한 “5명의 IQ 점수” 실험에서는 표본 평균이 95였습니다. 그러나 <a href="#fig-fig8-6" class="quarto-xref">Figure&nbsp;<span>8.6</span></a> 의 표본 분포는 이 실험이 별로 정확하지 않다는 사실을 알려줍니다. 만약 실험을 반복한다면, 표본 평균이 80에서 120 사이에서 변동할 가능성이 높습니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-6" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="h!" data-fig-align="left" alt="IQ 점수의 히스토그램과 그 위에 겹쳐진 정규 분포 곡선. x축은 60에서 140까지의 범위를 가지며, 100 부근에서 정점을 이룹니다. y축은 빈도를 나타냅니다. 히스토그램 막대는 파란색이며, 정규 분포 곡선은 검은색입니다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-6-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="h!" alt="IQ 점수의 히스토그램과 그 위에 겹쳐진 정규 분포 곡선. x축은 60에서 140까지의 범위를 가지며, 100 부근에서 정점을 이룹니다. y축은 빈도를 나타냅니다. 히스토그램 막대는 파란색이며, 정규 분포 곡선은 검은색입니다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.6. 5명의 IQ 점수 실험에서 평균의 표본 분포. 무작위로 5명을 표본으로 선정하여 그들의 평균 IQ를 계산하면 거의 확실히 80에서 120 사이의 값을 얻게 됩니다. 하지만 120을 초과하거나 80 미만의 IQ를 가진 사람이 꽤 많음에도 불구하고, 이러한 값이 나오기는 어렵습니다. 비교를 위해, 검은색 선은 모집단의 IQ 분포를 나타냅니다.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="모든-표본-통계량에는-표본-분포가-존재한다" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="모든-표본-통계량에는-표본-분포가-존재한다"><span class="header-section-number">8.3.2</span> 모든 표본 통계량에는 표본 분포가 존재한다!</h3>
<p>표본 분포에 대해 생각할 때 기억해야 할 중요한 점은, 우리가 계산할 수 있는 모든 표본 통계량에는 표본 분포가 존재한다는 것입니다. 예를 들어, “5명의 IQ 점수” 실험을 반복할 때마다 그 실험에서 가장 높은 IQ 점수를 기록한다고 가정해 봅시다. 그러면 다음과 같은 데이터 집합이 형성될 것입니다.</p>
<blockquote class="blockquote">
<p>110 117 122 119 113 …</p>
</blockquote>
<p>이 과정을 계속 반복하면 전혀 다른 표본 분포가 생성됩니다. 즉, 이는 최대값의 표본 분포입니다. 5명의 IQ 점수 중 최대값의 표본 분포는 <a href="#fig-fig8-7" class="quarto-xref">Figure&nbsp;<span>8.7</span></a> 에서 확인할 수 있습니다. 예상할 수 있듯이, 무작위로 5명을 선정한 후 가장 높은 IQ 점수를 가진 사람을 찾으면, 그 사람은 평균 이상의 IQ를 가지고 있을 가능성이 큽니다. 대부분의 경우, IQ가 100에서 140 사이인 사람을 얻게 될 것입니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-7" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="IQ 점수의 히스토그램으로, 파란색 막대가 각 점수 범위의 빈도를 나타낸다. 검은색 종곡선이 정규 분포를 나타내며, x축은 60에서 140까지의 점수 범위를 가진다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-7-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H" alt="IQ 점수의 히스토그램으로, 파란색 막대가 각 점수 범위의 빈도를 나타낸다. 검은색 종곡선이 정규 분포를 나타내며, x축은 60에서 140까지의 점수 범위를 가진다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.7. 5명의 IQ 점수 실험에서 최대값의 표본 분포. 무작위로 5명을 선정한 후 가장 높은 IQ 점수를 가진 사람을 선택하면, 대부분 IQ가 100에서 140 사이에 위치할 것이다.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-The-central-limit-theorem" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="sec-The-central-limit-theorem"><span class="header-section-number">8.3.3</span> 중심극한정리</h3>
<p>이제 표본 분포가 무엇인지, 특히 평균의 표본 분포가 무엇인지에 대해 어느 정도 이해했을 것입니다. 이번 절에서는 표본 평균의 분포가 표본 크기에 따라 어떻게 변하는지 이야기하고자 합니다. 직관적으로, 여러분은 이미 답의 일부를 알고 있습니다. 표본 크기가 작으면 표본 평균이 부정확할 가능성이 큽니다. 작은 실험을 반복하여 평균을 다시 계산하면 매우 다른 값을 얻게 될 것입니다. 즉, 표본 분포의 폭이 넓다는 뜻입니다. 반대로, 큰 실험을 반복하여 표본 평균을 다시 계산하면 이전 실험과 거의 동일한 값을 얻을 것이므로 표본 분포가 매우 좁아집니다. 이를 시각적으로 <a href="#fig-fig8-8" class="quarto-xref">Figure&nbsp;<span>8.8</span></a> 에서 확인할 수 있습니다. 표본 크기가 커질수록 표본 분포가 좁아지는 것을 볼 수 있습니다. (a)에서는 각 데이터 세트에 단 하나의 관측값만 포함되어 있어, 각 표본의 평균이 한 개인의 IQ 점수와 동일합니다. 따라서 평균의 표본 분포는 당연히 IQ 점수의 모집단 분포와 동일합니다. 그러나 표본 크기를 2로 늘리면 개별적인 IQ 점수보다 표본 평균이 모집단 평균에 더 가까워지는 경향이 있으며, 따라서 히스토그램(즉, 표본 분포)이 모집단 분포보다 약간 좁아집니다. 표본 크기를 10으로 늘리면 (c)에서 볼 수 있듯이, 표본 평균의 분포가 모집단 평균 주위에 꽤 밀집되는 경향이 있습니다. 이러한 효과는 <strong>표준 오차</strong>(standard error)라고 하는 <em>표본 분포의 표준 편차</em>를 계산하여 정량화할 수 있습니다. 표준 오차는 일반적으로 SE로 표시되며, 우리가 주로 관심을 가지는 표본 평균의 표준 오차는 SEM이라는 약어를 사용합니다. 그림에서 확인할 수 있듯이, 표본 크기 <span class="math inline">\(N\)</span>이 증가할수록 SEM은 감소합니다.<br>
</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-8" class="quarto-float quarto-figure quarto-figure-left anchored" alt="세 개의 히스토그램이 서로 다른 표본 크기에 따른 IQ 점수의 분포를 나타냄. (a) 표본 크기 1, 넓은 분포. (b) 표본 크기 2, 더 좁은 분포. (c) 표본 크기 10, 가장 좁은 분포. 모든 그래프에 정규 분포 곡선이 겹쳐져 있음." data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-8-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:100.0%" alt="세 개의 히스토그램이 서로 다른 표본 크기에 따른 IQ 점수의 분포를 나타냄. (a) 표본 크기 1, 넓은 분포. (b) 표본 크기 2, 더 좁은 분포. (c) 표본 크기 10, 가장 좁은 분포. 모든 그래프에 정규 분포 곡선이 겹쳐져 있음.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.8. 표본 크기에 따른 평균의 표본 분포 변화. 각 패널에서 IQ 데이터 10,000개 표본을 생성하고, 각 표본 내에서 평균 IQ를 계산하였습니다. 히스토그램은 이러한 평균들의 분포(즉, 평균의 표본 분포)를 나타냅니다. 개별적인 IQ 점수는 평균 100, 표준 편차 15인 정규 분포에서 추출되었으며, 검은 실선이 이를 나타냅니다.
</figcaption>
</figure>
</div>
</div>
</div>
<p>이제까지 한 가지 중요한 사실을 설명했습니다. 그러나 지금까지 간과했던 점이 하나 있습니다. 앞선 모든 예제는 “IQ 점수” 실험을 기반으로 하였으며, IQ 점수는 대략 정규 분포를 따르므로 모집단 분포도 정규 분포라고 가정했습니다. 그런데 모집단 분포가 정규 분포가 아니라면 어떻게 될까요? 평균의 표본 분포는 어떻게 변할까요? 놀라운 점은 모집단 분포의 모양이 어떠하든 간에 표본 크기 <span class="math inline">\(N\)</span>이 커질수록 평균의 표본 분포는 점점 정규 분포에 가까워진다는 것입니다. 이를 보여주기 위해 몇 가지 시뮬레이션을 수행했습니다. 먼저, <a href="#fig-fig8-9" class="quarto-xref">Figure&nbsp;<span>8.9</span></a> 히스토그램으로 나타낸 “비대칭” 분포에서 시작했습니다. 검은 실선으로 표시된 종 모양의 곡선과 삼각형 모양의 히스토그램을 비교하면 모집단 분포가 정규 분포와 전혀 닮지 않았음을 알 수 있습니다. 다음으로, 이 분포에서 <span class="math inline">\(N = 2\)</span>개의 표본을 추출하여 실험을 여러 번 수행한 후, 표본 평균을 계산했습니다. <a href="#fig-fig8-9" class="quarto-xref">Figure&nbsp;<span>8.9</span></a> (b)는 이 표본 평균들의 히스토그램(즉, 평균의 표본 분포)을 나타냅니다. 여전히 정규 분포는 아니지만, 모집단 분포(<a href="#fig-fig8-9" class="quarto-xref">Figure&nbsp;<span>8.9</span></a> (a))보다는 검은 실선에 훨씬 더 가까워졌습니다. 표본 크기를 <span class="math inline">\(N = 4\)</span>로 늘리면 평균의 표본 분포는 거의 정규 분포(<a href="#fig-fig8-9" class="quarto-xref">Figure&nbsp;<span>8.9</span></a> (c))와 유사해지며, <span class="math inline">\(N = 8\)</span>에 도달하면 거의 완벽한 정규 분포를 이룹니다. 즉, 표본 크기가 너무 작지만 않다면 모집단 분포의 형태와 관계없이 평균의 표본 분포는 대략 정규 분포를 따릅니다!</p>
<p>이제 우리는 평균의 표본 분포에 대해 다음과 같은 중요한 사실을 확인할 수 있습니다.</p>
<ul>
<li>평균의 표본 분포에서는 평균이 모집단 평균과 동일하다.</li>
<li>평균의 표본 분포에서는 표준 편차(즉, 표준 오차)는 표본 크기가 증가할수록 작아진다.</li>
<li>평균의 표본 분포에서는 표본 크기가 증가할수록 정규 분포에 가까워진다.</li>
</ul>
<p>이러한 사실은 단순한 경험적 관찰이 아니라, 통계학에서 가장 유명한 정리 중 하나인 <strong>중심극한정리</strong>(central limit theorem)에 의해 수학적으로 증명됩니다. 중심극한정리는 다음을 포함한 여러 가지 중요한 내용을 포함하고 있습니다. 모집단 분포의 평균이 <span class="math inline">\(\mu\)</span>, 표준 편차가 <span class="math inline">\(\sigma\)</span>일 때, 평균의 표본 분포 또한 평균 <span class="math inline">\(\mu\)</span>를 가지며 표준 오차는 다음과 같이 계산됩니다.</p>
<p><span class="math display">\[SEM=\frac{\sigma}{\sqrt{N}}\]</span></p>
<p>즉, 모집단의 표준 편차 <span class="math inline">\(\sigma\)</span>를 표본 크기 <span class="math inline">\(N\)</span>의 제곱근으로 나누므로, 표본 크기가 커질수록 SEM은 감소합니다. 또한 중심극한정리는 평균의 표본 분포가 점점 정규 분포에 가까워진다고 알려줍니다.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>이 결과는 여러 가지 측면에서 유용합니다. 이는 왜 큰 규모의 실험이 작은 실험보다 신뢰할 만한지를 설명해주며, 표준 오차에 대한 명확한 공식을 제공함으로써 큰 실험이 얼마나 더 신뢰할 만한지를 알려줍니다. 또한, 정규 분포가 왜 그렇게 “일반적(normal)”인지에 대한 이유도 설명해줍니다. 실제 실험에서 우리가 측정하고자 하는 많은 것들은 사실 여러 가지 다른 양들의 평균값입니다. (예를 들어, IQ로 측정되는 “일반적인” 지능은 많은 “특정한” 기술과 능력들의 평균이라고 볼 수 있습니다.) 이러한 경우, 평균이 된 값은 정규 분포를 따르게 됩니다. 이 수학적 법칙 덕분에, 정규 분포는 실제 데이터에서 반복적으로 나타납니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-9" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="네 개의 히스토그램이 서로 다른 표본 크기에 따른 표본 평균의 분포를 나타냅니다. (a) 표본 크기 1, (b) 표본 크기 2, (c) 표본 크기 4, (d) 표본 크기 8. 표본 크기가 증가할수록 오른쪽으로 치우친 분포가 정규 분포 형태로 변화합니다. 모든 x축은 &quot;표본 평균&quot;으로 표시되어 있습니다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-9-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H" alt="네 개의 히스토그램이 서로 다른 표본 크기에 따른 표본 평균의 분포를 나타냅니다. (a) 표본 크기 1, (b) 표본 크기 2, (c) 표본 크기 4, (d) 표본 크기 8. 표본 크기가 증가할수록 오른쪽으로 치우친 분포가 정규 분포 형태로 변화합니다. 모든 x축은 &quot;표본 평균&quot;으로 표시되어 있습니다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.9. 중심극한정리의 시각적 설명. (a)에서는 모집단 분포가 정규 분포가 아니지만, (b)-(d)에서는 표본 크기가 2, 4, 8로 증가함에 따라 평균의 표본 분포가 정규 분포에 가까워지는 것을 볼 수 있습니다.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="모집단-모수-추정하기" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="모집단-모수-추정하기"><span class="header-section-number">8.4</span> 모집단 모수 추정하기</h2>
<p>이전 절의 모든 IQ 예제에서는 실제로 모집단 모수를 미리 알고 있었습니다. 지능 측정에 대한 첫 번째 강의에서 모든 학부생이 배우듯이, IQ 점수는 평균이 100이고 표준편차가 15가 되도록 정의되어 있습니다. 그러나 이것은 약간의 “거짓말”입니다. 어떻게 IQ 점수가 실제 모집단 평균이 100이라고 알 수 있을까요? 이는 테스트를 설계한 사람들이 매우 큰 표본에 대해 테스트를 실시하고, 그들의 표본이 평균 100이 되도록 <em>점수 규칙을 조정했기 때문</em>입니다. 물론 이것은 나쁜 일이 아닙니다. 이는 심리학적 측정을 설계하는 데 있어 중요한 부분입니다. 하지만 이 이론적 평균 100은 테스트 설계자들이 사용한 모집단에만 해당된다는 점을 기억하는 것이 중요합니다. 좋은 테스트 설계자들은 실제로 다양한 모집단(예: 연령대, 국적 등)에 적용할 수 있는 “테스트 기준”을 제공하기 위해 상당한 노력을 기울입니다.</p>
<p>이러한 기준은 매우 유용하지만, 대부분의 연구는 이러한 기준이 만들어진 모집단과는 다른 사람들을 대상으로 합니다. 예를 들어, 남호주 산업 도시인 포트 피리(Port Pirie)에서 저수준 납 중독이 인지 기능에 미치는 영향을 측정하고 싶다고 가정해 보겠습니다. 포트 피리에는 납 제련소가 있습니다. 아마도 포트 피리 사람들의 IQ 점수를 같은 남호주의 산업 도시인 와이알라(Whyalla)의 사람들과 비교하고 싶을 것입니다. 와이알라에는 강철 제련소가 있습니다.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a><br>
어느 도시를 연구하든 모집단의 실제 평균 IQ가 100이라고 단순히 가정하는 것은 타당하지 않습니다. 남호주의 산업 도시에 자동으로 적용할 수 있는 신뢰할 만한 기준 데이터를 가진 사람은 제가 알기로는 없습니다.<br>
따라서 우리는 데이터 표본을 통해 <strong>모집단 모수를 추정</strong>해야 합니다. 그렇다면 이 작업을 어떻게 수행할 수 있을까요?</p>
<section id="모집단-평균-추정하기" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="모집단-평균-추정하기"><span class="header-section-number">8.4.1</span> 모집단 평균 추정하기</h3>
<p>포트 피리에서 100명의 주민이 IQ 테스트를 받아주었다고 가정해 보겠습니다. 이들의 평균 IQ 점수는 <span class="math inline">\(\bar{X} = 98.5\)</span>로 나타났습니다. 그렇다면 포트 피리 전체 모집단의 실제 평균 IQ는 얼마일까요? 당연히 정확한 답은 알 수 없습니다. 진짜 평균이 97.2일 수도 있고, 103.5일 수도 있습니다. 우리의 표본이 포괄적이지 않기 때문에 확정적인 답을 내릴 수 없습니다. 그렇더라도 <strong>“최선의 추정값”</strong>을 말해야 한다면, 저는 98.5라고 대답할 것입니다. 이것이 바로 <strong>통계적 추정(statistical estimation)의 본질</strong>입니다: 최선의 추정(best guess)을 제시하는 것.</p>
<p>이 예제에서는 미지의 모집단 모수에 대한 추정이 간단합니다. 표본 평균(sample mean)을 계산하고, 이를 모집단 평균(population mean)의 추정치로 사용합니다. 매우 단순해 보이지만, 다음 절에서는 이 직관적인 답변에 대한 통계적 근거를 설명하겠습니다. 다만, 지금 중요한 것은 <strong>표본 통계량(sample statistic)</strong>과 <strong>모집단 모수의 추정치(estimate of the population parameter)</strong>가 개념적으로 다르다는 점을 인식하는 것입니다.</p>
<ul>
<li>표본 통계량은 데이터의 기술적 설명입니다.<br>
</li>
<li>모수의 추정치는 모집단에 대한 추정값입니다.</li>
</ul>
<p>이러한 차이를 명확히 하기 위해, 통계학자들은 서로 다른 표기법을 사용합니다.</p>
<ul>
<li>모집단의 실제 평균이 <span class="math inline">\(\mu\)</span>로 표시된다면,<br>
</li>
<li>모집단 평균의 추정치는 <span class="math inline">\(\hat{\mu}\)</span>로 표시합니다.<br>
</li>
<li>반면, 표본 평균은 <span class="math inline">\(\bar{X}\)</span> 또는 경우에 따라 <span class="math inline">\(m\)</span>으로 표시됩니다.</li>
</ul>
<p>하지만 단순 무작위 표본의 경우, 모집단 평균의 추정치는 표본 평균과 동일합니다. 예를 들어, 표본 평균이 <span class="math inline">\(\bar{X} = 98.5\)</span>라면, 모집단 평균의 추정치도 <span class="math inline">\(\hat{\mu} = 98.5\)</span>가 됩니다. 표기법을 명확하게 정리하기 위해, 아래 표(<a href="#tbl-tab8-2" class="quarto-xref">Table&nbsp;<span>8.2</span></a>)를 참고하세요.</p>
<div class="cell" data-layout-align="left">
<div id="tbl-tab8-2" class="cell quarto-float quarto-figure quarto-figure-left anchored" data-layout-align="left">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tab8-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.2. 평균에 대한 표기법
</figcaption>
<div aria-describedby="tbl-tab8-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:tbl-tab8-2">
<colgroup><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: bold;">기호</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">의미</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: bold;">우리가 알고 있는가?</th></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \hat{X} \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">표본 평균</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">예, 원본 데이터에서 계산됨</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \mu \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">모집단 평균</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">거의 알 수 없음</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \hat{\mu} \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">모집단 평균의 추정치</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">예, 단순 랜덤 표본에서는 표본 평균과 동일</td></tr>
</tbody></table>

</div>
</div>
</figure>
</div>
</div>
</section>
<section id="모집단-표준편차-추정하기" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="모집단-표준편차-추정하기"><span class="header-section-number">8.4.2</span> 모집단 표준편차 추정하기</h3>
<p>지금까지 추정은 꽤 단순해 보였고, 아마도 왜 제가 여러분에게 표본 이론에 대한 모든 내용을 읽게 했는지 궁금할 수 있습니다. 평균의 경우, 모집단 모수의 추정치(즉, <span class="math inline">\(\hat{\mu}\)</span>)는 해당 표본 통계량(즉, <span class="math inline">\(\bar{X}\)</span>)과 동일했습니다. 하지만 항상 그런 것은 아닙니다. 이를 이해하기 위해 <strong>모집단 표준편차의 추정치</strong>를 어떻게 구성할 수 있는지 생각해 보겠습니다. 이 추정치는 <span class="math inline">\(\hat{\sigma}\)</span>로 나타내겠습니다. 이 경우 무엇을 추정치로 사용해야 할까요? 처음에는 평균을 추정할 때 했던 것처럼 표본 통계량을 그대로 사용하면 된다고 생각할 수 있습니다. 거의 맞는 생각이지만, 완전히 옳지는 않습니다.</p>
<p>그 이유는 이렇습니다. 하나의 관측값만 포함된 표본이 있다고 가정해 보겠습니다. 이 예에서는 실제 모집단에 대한 직관이 허용되지 않는 상황을 고려하는 것이 도움이 되므로, 완전히 허구의 예를 사용하겠습니다. 예를 들어, 제 신발의 “크로뮬런스(cromulence)”를 측정했다고 합시다. 측정 결과 제 신발의 크로뮬런스는 <span class="math inline">\(20\)</span>이었습니다. 즉, 표본은 다음과 같습니다:<br>
<span class="math display">\[20\]</span></p>
<p>이 표본은 표본 크기 <span class="math inline">\(N = 1\)</span>인 완전히 유효한 표본입니다. 표본 평균은 <span class="math inline">\(20\)</span>이고, 표본의 모든 관측값이 (당연히) 표본 평균과 같기 때문에 표본 표준편차는 <span class="math inline">\(0\)</span>입니다. <em>표본</em>을 기술하는 데 있어서 이는 옳은 결과입니다. 표본이 하나의 관측값만 포함하고 있으므로 표본 내에서 관찰되는 변동성이 없는 것이 당연합니다. 따라서 표본 표준편차 <span class="math inline">\(s = 0\)</span>은 적절한 결과입니다. 하지만 이 값을 <em>모집단</em> 표준편차의 추정치로 사용하려고 하면 전혀 말이 안 되는 것처럼 느껴지지 않나요? 물론 “크로뮬런스”가 무엇인지 저도 여러분도 모르지만, 데이터에 대해서는 알고 있습니다. 표본에서 변동성이 보이지 않는 유일한 이유는 표본이 너무 작아서 변동성을 보여줄 수 없기 때문입니다! 따라서 표본 크기가 <span class="math inline">\(N = 1\)</span>일 경우 모집단의 표준편차에 대해서는 “모르겠다”라고 대답하는 것이 더 적절한 것처럼 느껴집니다.</p>
<p>하지만 표본 평균과 모집단 평균에 대해서는 같은 직관이 적용되지 않습니다. 모집단 평균에 대한 최선의 추측을 해야 한다면, <span class="math inline">\(20\)</span>이라고 추정하는 것이 비이성적인 선택은 아닙니다. 물론 단 하나의 관측값만으로는 그 추측에 자신이 없겠지만, 여전히 할 수 있는 최선의 추정입니다.</p>
<p>이 예를 조금 더 확장해 보겠습니다. 이번에는 신발의 크로뮬런스에 대한 관측값이 <span class="math inline">\(N = 2\)</span>개 있습니다. 전체 표본은 다음과 같습니다:<br>
<span class="math display">\[20, 22\]</span></p>
<p>이번에는 두 개의 관측값이 있어 변동성을 관찰할 수 있게 되었습니다. 변동성을 관찰하기 위해 필요한 최소한의 관측값은 두 개입니다! 새로운 데이터 세트에서 표본 평균은 <span class="math inline">\(\bar{X} = 21\)</span>, 표본 표준편차는 <span class="math inline">\(s = 1\)</span>입니다. 이제 모집단에 대해 어떤 직관을 얻을 수 있을까요? 모집단 평균의 경우, 최선의 추정치는 여전히 표본 평균입니다. 추측해야 한다면 모집단 평균 크로뮬런스가 <span class="math inline">\(21\)</span>이라고 예상할 것입니다. 그렇다면 표준편차는 어떨까요? 이 부분은 좀 더 복잡합니다. 표본 표준편차는 두 개의 관측값에 기반하고 있으며, 저처럼 느끼는 사람이라면 이 두 개의 관측값만으로는 모집단의 진정한 변동성을 충분히 드러내기에 부족하다고 직관적으로 생각할 것입니다. 단순히 추정치가 틀렸을 것이라고 예상하는 것이 아니라, 그 오차가 체계적일 것이라는 점이 걱정되는 것입니다. 구체적으로는, 표본 표준편차가 모집단 표준편차보다 작을 가능성이 높다고 의심하는 것입니다.</p>
<p>이 직관은 타당해 보이지만, 이를 실제로 보여주면 더 좋겠죠. 사실 이러한 직관을 수학적으로 증명할 수 있는 공식이 존재하지만, 관련 수학적 배경 지식이 없다면 그다지 도움이 되지 않습니다. 대신 몇 가지 실험 결과를 시뮬레이션하여 보여드리겠습니다. 이를 위해 다시 IQ 연구로 돌아가 보겠습니다. 모집단의 실제 평균 IQ가 <span class="math inline">\(100\)</span>, 표준편차가 <span class="math inline">\(15\)</span>라고 가정합시다. 먼저 <span class="math inline">\(N = 2\)</span>개의 IQ 점수를 측정한 후 표본 표준편차를 계산하는 실험을 진행합니다. 이 과정을 여러 번 반복하고, 이러한 표본 표준편차들의 히스토그램을 그리면 표준편차의 <strong>표본 분포(sampling distribution)</strong>를 얻을 수 있습니다. 이 분포를 <a href="#fig-fig8-10" class="quarto-xref">Figure&nbsp;<span>8.10</span></a> 에 나타냈습니다. 실제 모집단 표준편차는 15이지만, 이 실험에서는 평균적으로 약 8.4의 표준편차가 추정되어 실제 값보다 훨씬 낮은 결과를 보입니다! 즉, 표본 표준편차는 모집단 표준편차의 (편향된) 편의추정량(biased estimator)이라는 것입니다. 이는 모집단 평균이 <span class="math inline">\(100\)</span>일 때 표본 평균의 분포를 그렸던 <a href="#fig-fig8-8" class="quarto-xref">Figure&nbsp;<span>8.8</span></a> (b)의 결과와 매우 다릅니다. 당시에는 표본 평균의 평균값도 <span class="math inline">\(100\)</span>이었으므로, (편향되지 않은) 불편추정량(unbiased estimator)이였기 때문입니다.</p>
<p>이제 시뮬레이션을 확장해 보겠습니다. <span class="math inline">\(N=2\)</span>로 제한하지 않고, 표본 크기를 1부터 10까지로 늘려 실험을 반복합니다. 표본 평균과 표본 표준편차의 평균값을 표본 크기의 함수로 나타내면 <a href="#fig-fig8-11" class="quarto-xref">Figure&nbsp;<span>8.11</span></a> 같은 결과가 나옵니다. 이 그래프를 위해 관측값이 각각 1개인 데이터 세트를 10,000개, 관측값이 2개인 데이터 세트를 또 10,000개, 이렇게 표본 크기 10까지 시뮬레이션을 진행했습니다. 각 데이터 세트는 평균이 100, 표준편차가 15인 정규분포를 따르는 가상의 IQ 데이터로 구성했습니다. 결과적으로 표본 평균은 표본 크기에 상관없이 평균적으로 100이었으며(<a href="#fig-fig8-11" class="quarto-xref">Figure&nbsp;<span>8.11</span></a> (a)), 이는 모집단 평균과 같습니다. 즉, 불편추정량입니다. 이것이 바로 모집단 평균의 최선의 추정치로 표본 평균을 사용하는 이유입니다.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> 오른쪽 그래프((<a href="#fig-fig8-11" class="quarto-xref">Figure&nbsp;<span>8.11</span></a> (b))는 매우 다릅니다. 평균적으로 표본 표준편차 <span class="math inline">\(s\)</span>는 모집단 표준편차 <span class="math inline">\(\sigma\)</span>보다 작으며, 특히 표본 크기가 작을수록 이 경향이 두드러집니다. 즉, 표본 표준편차는 편의추정치입니다. 다시 말해, 모집단 표준편차 <span class="math inline">\(\hat{\sigma}\)</span>에 대한 최선의 추정치를 구하고 싶다면 표본 표준편차 <span class="math inline">\(s\)</span>보다 약간 더 큰 값을 선택해야 합니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-10" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="오른쪽으로 치우친 분포를 가진 히스토그램으로, x축은 0에서 60까지의 표본 표준편차, y축은 빈도를 나타냅니다. 모집단 표준편차로 표시된 점선은 x축의 약 16 지점에 위치해 있습니다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-10-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H" alt="오른쪽으로 치우친 분포를 가진 히스토그램으로, x축은 0에서 60까지의 표본 표준편차, y축은 빈도를 나타냅니다. 모집단 표준편차로 표시된 점선은 x축의 약 16 지점에 위치해 있습니다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.10. 두 개의 IQ 점수 실험에서의 표본 표준편차의 샘플링 분포. 실제 모집단의 표준편차는 15(점선)이며, 히스토그램에서 볼 수 있듯이 대부분의 실험은 이보다 훨씬 작은 표본 표준편차를 산출합니다.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-11" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="두 개의 선 그래프. (a) 그래프는 표본 평균의 평균과 표본 크기 간의 관계를 보여주며, 값은 대략 102-104 사이입니다. (b) 그래프는 표본 표준편차의 평균과 표본 크기 간의 관계를 보여주며, 처음에는 가파르게 증가하다가 표본 크기 8 근처에서 15로 수렴합니다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-11-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H" alt="두 개의 선 그래프. (a) 그래프는 표본 평균의 평균과 표본 크기 간의 관계를 보여주며, 값은 대략 102-104 사이입니다. (b) 그래프는 표본 표준편차의 평균과 표본 크기 간의 관계를 보여주며, 처음에는 가파르게 증가하다가 표본 크기 8 근처에서 15로 수렴합니다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.11. 표본 평균은 모집단 평균의 불편추정량이라는 그림 (a)와 표본 표준편차는 모집단 표준편차의 편의추정량이라는 것을 보여주는 그림 (b).
</figcaption>
</figure>
</div>
</div>
</div>
<p>이러한 체계적인 편향을 수정하는 방법은 매우 간단합니다. 어떻게 수정되는지 살펴보겠습니다. 표준편차를 다루기 전에 분산부터 살펴보겠습니다. <a href="#모집단-모수-추정하기">모집단 모수 추정하기</a> 절에서 설명한 바와 같이, 표본 분산은 표본 평균으로부터의 제곱 편차를 평균한 것으로 정의됩니다. 즉:<br>
<span class="math display">\[s^2=\frac{1}{N} \sum_{i=1}^{N}(X_i-\bar{X})^2\]</span><br>
표본 분산 <span class="math inline">\(s^2\)</span>은 모집단 분산 <span class="math inline">\(\sigma^2\)</span>의 편의추정량입니다. 하지만 약간의 수정을 가하면 불편추정량으로 변환할 수 있습니다. 단순히 <span class="math inline">\(N\)</span>이 아닌 <span class="math inline">\(N-1\)</span>로 나누기만 하면 됩니다.</p>
<p>이것이 모집단 분산 <span class="math inline">\(\sigma\)</span>의 불편추정량입니다. 이는 <a href="#모집단-모수-추정하기">모집단 모수 추정하기</a>에서 제기한 질문에 대한 답이기도 합니다. 왜 jamovi에서 분산 계산 결과가 약간 달랐을까요? 그것은 jamovi가 <span class="math inline">\(s^2\)</span>이 아닌 <span class="math inline">\(\hat{\sigma}^2\)</span>를 계산하기 때문입니다. 표준편차의 경우도 마찬가지입니다. <span class="math inline">\(N\)</span>이 아닌 <span class="math inline">\(N-1\)</span>로 나누면 모집단 표준편차의 불편추정량을 얻을 수 있습니다. jamovi의 내장 표준편차 함수를 사용할 때 계산되는 것은 <span class="math inline">\(s\)</span>가 아니라 <span class="math inline">\(\hat{\sigma}\)</span>입니다.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>마지막으로 한 가지 더. 실제로는 많은 사람들이 <span class="math inline">\(\hat{\sigma}\)</span> (즉, <span class="math inline">\(N-1\)</span>로 나누는 공식)를 표본 표준편차라고 부릅니다. 엄밀히 말하면 이는 틀린 표현입니다. 표본 표준편차는 <span class="math inline">\(s\)</span>(<span class="math inline">\(N\)</span>으로 나누는 공식)와 같아야 합니다. 이 둘은 개념적으로나 수치적으로 동일하지 않습니다. 하나는 표본의 특성이며, 다른 하나는 모집단의 특성에 대한 추정치입니다. 그러나 실제로 중요한 것은 모집단 모수의 추정치이기 때문에 대부분의 경우 <span class="math inline">\(\hat{\sigma}\)</span>를 보고합니다. 물론 이 수치가 보고되어야 할 정확한 결과입니다. 다만 “표본 표준편차”라는 표현이 “모집단 표준편차 추정치”보다 짧기 때문에 용어 사용이 다소 부정확해지는 경우가 있습니다. 이는 큰 문제가 아니며, 저 역시 다른 사람들과 같은 방식으로 사용합니다. 그럼에도 불구하고 두 개념을 구분하는 것이 중요하다고 생각합니다. “표본의 알려진 특성”과 “표본이 속한 모집단에 대한 추정”을 혼동하는 것은 결코 좋은 생각이 아닙니다. <span class="math inline">\(s\)</span>와 <span class="math inline">\(\hat{\sigma}\)</span>를 동일하게 여기기 시작하는 순간, 바로 그 혼동이 발생하게 됩니다.</p>
<p>이 섹션을 마무리하며 개념을 더 명확히 하기 위해 추가적인 표를 제공합니다 (<a href="#tbl-tab8-3" class="quarto-xref">Table&nbsp;<span>8.3</span></a> and <a href="#tbl-tab8-4" class="quarto-xref">Table&nbsp;<span>8.4</span></a>).</p>
<div class="cell" data-layout-align="left">
<div id="tbl-tab8-3" class="cell quarto-float quarto-figure quarto-figure-left anchored" data-layout-align="left">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tab8-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.3. 표준편차 표기법
</figcaption>
<div aria-describedby="tbl-tab8-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:tbl-tab8-3">
<colgroup><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: bold;">기호</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">의미</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: bold;">우리가 알고 있는가?</th></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( s \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">표본 표준편차</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">예, 원본 데이터에서 계산됨</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \sigma  \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">모집단 표분편차</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">거의 알 수 없음</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \hat{\sigma } \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">모집단 표준편차의 추정치</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">예, 그러나 표본표준편차와 같지 않음</td></tr>
</tbody></table>

</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="left">
<div id="tbl-tab8-4" class="cell quarto-float quarto-figure quarto-figure-left anchored" data-layout-align="left">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tab8-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.4. 분산 표기법
</figcaption>
<div aria-describedby="tbl-tab8-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:tbl-tab8-4">
<colgroup><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: bold;">기호</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: bold;">의미</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: bold;">우리가 알고 있는가?</th></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( s^2 \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">표본 분산</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">예, 원본 데이터에서 계산됨</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \sigma^2  \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">모집단 분산</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">거의 알 수 없음</td></tr>
<tr>
<td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 0pt; font-weight: normal;">\( \hat{\sigma }^2 \)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 12pt 2pt 12pt; font-weight: normal;">모집단 분산의 추정치</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 2pt 0pt 2pt 12pt; font-weight: normal;">예, 그러나 표본분산과 같지 않음</td></tr>
</tbody></table>

</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="sec-Estimating-a-confidence-interval" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-Estimating-a-confidence-interval"><span class="header-section-number">8.5</span> 신뢰구간 추정</h2>
<blockquote class="blockquote">
<p><em>통계학이란 무엇이 확실하다고 말할 필요가 없다는 것을 의미한다</em><br>
– 출처 불명<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
</blockquote>
<p>이 장의 지금까지는 통계학자들이 표본 데이터를 바탕으로 모집단의 모수를 추정할 때 사용하는 표본 이론의 기본 개념을 설명했습니다. 이러한 논의에서 알 수 있듯이, 우리가 이러한 표본 이론이 필요한 이유 중 하나는 모든 데이터 세트에는 일정한 불확실성이 있기 때문에 우리의 추정치는 결코 완벽하게 정확할 수 없다는 점입니다. 그러나 이 논의에서 빠진 부분은 바로 이러한 추정치에 수반되는 불확실성의 정도를 정량화하려는 시도입니다. 예를 들어, 심리학과 학부생의 평균 IQ가 <span class="math inline">\(115\)</span>라고 추정한다고 가정합시다(이 숫자는 단순한 예일 뿐입니다). 여기서 끝나는 것이 아니라, 우리는 이 추정치에 대한 확신의 정도를 표현할 수 있기를 원합니다. 예를 들어, 실제 평균이 <span class="math inline">\(109\)</span>와 <span class="math inline">\(121\)</span> 사이에 있을 확률이 <span class="math inline">\(95\%\)</span>라고 말할 수 있다면 더 좋을 것입니다. 이를 평균의 <strong>신뢰구간(confidence interval)</strong>이라고 부릅니다.</p>
<p>표본 분포에 대한 이해를 바탕으로 평균의 신뢰구간을 구성하는 것은 실제로 매우 간단합니다. 방법은 다음과 같습니다. 모집단의 실제 평균이 <span class="math inline">\(\mu\)</span>, 표준 편차가 <span class="math inline">\(\sigma\)</span>라고 가정합니다. 이제 <span class="math inline">\(N\)</span>명의 참가자를 대상으로 연구를 완료했고, 이들의 평균 IQ는 <span class="math inline">\(\bar{X}\)</span>입니다. <a href="#sec-The-central-limit-theorem">중심극한정리</a>에 대한 논의에서 알 수 있듯이, 평균의 표본 분포는 대략 정규 분포를 따릅니다. 또한 <a href="07-Introduction-to-probability.html#sec-The-normal-distribution">정규 분포</a>에 대한 논의에서, 정규 분포된 값이 실제 평균으로부터 약 두 표준 편차 이내에 있을 확률이 <span class="math inline">\(95\%\)</span>라는 것을 배웠습니다.</p>
<p>좀 더 정확히 말하자면, 실제로는 정규 분포된 값이 실제 평균으로부터 <span class="math inline">\(1.96\)</span> 표준 편차 이내에 있을 확률이 <span class="math inline">\(95\%\)</span>입니다. 다음으로, 표본 분포의 표준 편차를 <strong>표준 오차</strong>(standard error)라고 하며, 평균의 표준 오차는 <strong>SEM</strong>으로 표기한다는 점을 기억하세요. 이러한 요소들을 모두 조합하면, 실제로 관측된 표본 평균 <span class="math inline">\(\bar{X}\)</span>가 모집단 평균으로부터 <span class="math inline">\(1.96\)</span> 표준 오차 이내에 있을 확률이 <span class="math inline">\(95\%\)</span>라는 것을 알 수 있습니다.</p>
<p>물론, <span class="math inline">\(1.96\)</span>이라는 숫자가 특별한 것은 아닙니다. 단지 <span class="math inline">\(95\%\)</span> 신뢰구간을 원할 때 사용하는 곱셈 인자일 뿐입니다. 만약 <span class="math inline">\(70\%\)</span> 신뢰구간을 원한다면, <span class="math inline">\(1.96\)</span> 대신 <span class="math inline">\(1.04\)</span>를 사용하면 됩니다.</p>
<p>수학적으로 이것은 다음과 같이 표현할 수 있습니다:<br>
<span class="math display">\[\mu - (1.96 \times SEM) \leq \bar{X} \leq \mu + (1.96 \times SEM)\]</span><br>
여기서 <span class="math inline">\(SEM = \frac{\sigma}{\sqrt{N}}\)</span>이며, 이 부등식이 성립할 확률은 <span class="math inline">\(95\%\)</span>입니다. 그러나 이 식은 우리가 실제로 알고자 하는 질문에 대한 답은 아닙니다. 이 식은 모집단의 모수를 알고 있을 때 표본 평균에 대해 예상할 수 있는 내용을 보여줍니다. 우리가 원하는 것은 이 과정을 반대로 적용하는 것입니다. 즉, 특정 표본을 관측한 상황에서 모집단 모수에 대해 어떤 추정을 할 수 있는지 알고 싶습니다. 그러나 이를 수행하는 것은 어렵지 않습니다. 약간의 고등학교 수준의 대수학을 활용하면, 이 식을 다음과 같이 변형할 수 있습니다:<br>
<span class="math display">\[\bar{X} - (1.96 \times SEM) \leq \mu \leq \bar{X} + (1.96 \times SEM)\]</span><br>
이 식은 이 범위가 모집단 평균 <span class="math inline">\(\mu\)</span>를 포함할 확률이 <span class="math inline">\(95\%\)</span>임을 의미합니다. 이 범위를 <strong>95% 신뢰구간</strong>이라고 하며, <span class="math inline">\(CI_{95}\)</span>로 표기합니다. 요약하면, <span class="math inline">\(N\)</span>이 충분히 크고(즉, 평균의 표본 분포가 정규 분포라고 가정할 수 있을 만큼 충분히 큰 경우), 다음과 같은 95% 신뢰구간 공식을 사용할 수 있습니다:<br>
<span class="math display">\[CI_{95} = \bar{X} \pm (1.96 \times \frac{\sigma}{\sqrt{N}})\]</span></p>
<section id="신뢰구간-해석하기" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="신뢰구간-해석하기"><span class="header-section-number">8.5.1</span> 신뢰구간 해석하기</h3>
<p>신뢰구간에서 가장 어려운 점은 그것이 의미하는 바를 이해하는 것입니다. 사람들이 신뢰구간을 처음 접할 때 거의 항상 드는 첫 번째 본능적인 반응은 “실제 평균(true mean)이 신뢰구간 안에 있을 확률이 95%다”라고 말하는 것입니다. 이 표현은 단순하고, “95%의 확신(confidence)”을 가진다는 것이 무엇을 의미하는지에 대한 상식적인 개념을 포착하는 것처럼 보입니다.</p>
<p>하지만 이 표현은 정확하지 않습니다. 이 직관적인 정의는 모집단 평균(population mean)의 값에 대한 개인적인 믿음에 매우 크게 의존합니다. “나는 95% 확신한다”라고 말하는 이유는 그것이 나의 믿음이기 때문입니다. 일상 생활에서는 이것이 전혀 문제되지 않지만, [확률이란 무엇을 의미하는가?] 절을 떠올려 보면, 개인적인 믿음과 확신에 대해 이야기하는 것은 베이지안(Bayesian) 관점이라는 것을 알 수 있습니다.</p>
<p>그러나 신뢰구간은 베이지안 도구가 아닙니다. 이 장의 다른 모든 내용과 마찬가지로 신뢰구간은 빈도주의자의 도구입니다. 빈도주의적 방법을 사용할 경우, 베이지안 해석을 적용하는 것은 적절하지 않습니다. 빈도주의적 방법을 사용할 때는 빈도주의자의 해석을 따라야 합니다!</p>
<p>그렇다면 올바른 해석은 무엇일까요? 빈도주의자 관점의 확률에 대해 우리가 말한 내용을 기억해 보세요. 우리가 “확률적 진술”을 할 수 있는 유일한 방법은 일련의 사건에 대해 이야기하고, 다양한 유형의 사건들이 발생하는 빈도를 세는 것입니다. 이 관점에서 95% 신뢰구간의 해석은 반드시 반복과 관련이 있어야 합니다. 구체적으로 말하자면, 만약 우리가 동일한 실험을 여러 번 반복하고, 각 반복마다 95% 신뢰구간을 계산한다면, 그 신뢰구간들 중 약 95%는 실제 평균을 포함하게 될 것입니다. 더 일반적으로 말하면, 이러한 절차를 사용하여 생성된 모든 신뢰구간의 95%는 실제 모집단 평균을 포함해야 합니다.</p>
<p>이 개념은 <a href="#fig-fig8-12" class="quarto-xref">Figure&nbsp;<span>8.12</span></a> 에 나와 있으며, 이는 “IQ 점수 10개 측정” 실험(상단 그림)과 “IQ 점수 25개 측정” 실험(하단 그림)에 대해 각각 50개의 신뢰구간을 생성한 결과를 보여줍니다. 우리는 대략 95%의 신뢰구간이 진짜 모집단 평균을 포함할 것으로 예상하며, 실제로 <a href="#fig-fig8-12" class="quarto-xref">Figure&nbsp;<span>8.12</span></a> 에서 이를 확인할 수 있습니다.</p>
<p>여기서 중요한 차이점은, 베이지안 주장은 모집단 평균 자체에 대한 확률적 진술을 한다는 점입니다. 즉, 모집단 평균에 대한 우리의 불확실성을 언급하는 것이죠. 그러나 빈도주의자 해석에서는 모집단을 “반복”할 수 없기 때문에 이러한 방식의 확률적 진술은 허용되지 않습니다.</p>
<p>빈도주의자 관점에서는 모집단 평균이 고정된 값이며, 이에 대해 확률적 진술을 할 수는 없습니다. 그러나 신뢰구간은 반복 가능한 것이며, 이에 대한 실험을 여러 번 반복할 수 있습니다. 따라서 <em>빈도주의자</em>는 <em>신뢰구간</em>이 실제 평균을 포함할 확률에 대해서는 이야기할 수 있지만, <em>실제 모집단 평균</em>이 신뢰구간 안에 포함될 확률에 대해서는 이야기할 수 없습니다. 왜냐하면 모집단 평균은 반복 가능한 사건이 아니기 때문입니다.</p>
<p>이 점이 다소 까다롭게 느껴질 수 있지만, 중요한 부분입니다. 해석의 차이는 수학적 접근의 차이로 이어지기 때문입니다. 신뢰구간의 베이지안 대안으로는 <em>신용구간(credible interval)</em>이라는 개념이 있습니다. 대부분의 상황에서 신뢰구간과 신용구간은 매우 유사하지만, 경우에 따라 극적으로 다를 수 있습니다. 약속한 대로, 베이지안 관점에 대해서는 <a href="16-Bayesian-statistics.html" class="quarto-xref"><span>Chapter 16</span></a> 에서 더 자세히 설명하겠습니다.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-fig8-12" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-pos="H" data-fig-align="left" alt="두 개의 막대 그래프가 수직으로 표시되어 있습니다. 상단 그래프 (a)는 표본 크기 = 10, 하단 그래프(b)는 표본 크기 = 25로 표시되어 있습니다. 두 그래프 모두 x축에는 반복 횟수, y축에는 오차 막대가 있는 IQ 평균 값이 나타나 있습니다. 파란색 데이터 포인트에는 별표가 표시되어 있습니다.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fig8-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-Estimating-unknown-quantities-from-a-sample_files/figure-html/fig-fig8-12-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H" alt="두 개의 막대 그래프가 수직으로 표시되어 있습니다. 상단 그래프 (a)는 표본 크기 = 10, 하단 그래프(b)는 표본 크기 = 25로 표시되어 있습니다. 두 그래프 모두 x축에는 반복 횟수, y축에는 오차 막대가 있는 IQ 평균 값이 나타나 있습니다. 파란색 데이터 포인트에는 별표가 표시되어 있습니다.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fig8-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.12. 95% 신뢰구간. 상단 그래프 (a)는 10명의 IQ를 측정한 실험을 50번 시뮬레이션한 결과를 보여줍니다. 점은 표본 평균의 위치를 표시하며, 선은 95% 신뢰구간을 나타냅니다. 50개의 신뢰구간 중 대부분은 실제 평균(즉, 100)을 포함하고 있지만, 파란색과 별표(*)로 표시된 일부 신뢰구간은 그렇지 않습니다. 하단 그래프 (b)는 25명의 IQ를 측정한 실험을 시뮬레이션한 결과를 보여줍니다.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="jamovi에서-신뢰구간-계산하기" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="jamovi에서-신뢰구간-계산하기"><span class="header-section-number">8.5.2</span> jamovi에서 신뢰구간 계산하기</h3>
<p>jamovi에는 ‘기술통계’ 기능을 통해 평균에 대한 신뢰구간을 간단히 계산할 수 있는 방법이 포함되어 있습니다. ‘기술통계’ 창의 ‘통계’ 옵션에는 ’평균에 대한 표준오차’와 ’평균에 대한 신뢰구간’을 선택할 수 있는 체크박스가 있습니다. 이 기능을 사용하면 기본값인 95% 신뢰구간을 확인할 수 있습니다.</p>
<p>예를 들어, <em>IQsim.omv</em> 파일을 불러온 후 ’평균에 대한 신뢰구간’을 선택하면, 시뮬레이션된 평균 IQ에 대한 신뢰구간을 확인할 수 있습니다. 하한 95% 신뢰구간 = 99.39, 상한 95% 신뢰구간 = 99.97로 표시됩니다. 따라서 <span class="math inline">\(N = 10,000\)</span>인 시뮬레이션된 대규모 표본 데이터에서 평균 IQ 점수는 99.68이며, 95% 신뢰구간은 99.39에서 99.97 사이입니다.</p>
<p>jamovi에서 신뢰구간을 시각화할 때는 박스 도표 옵션에서 평균을 포함하도록 지정할 수 있습니다. 또한, <a href="13-Comparing-several-means-one-way-ANOVA.html" class="quarto-xref"><span>Chapter 13</span></a> 절에서 배우게 될 일원 분산 분석(ANOVA)과 같은 특정 통계 검정을 사용할 때도 신뢰구간을 데이터 분석의 일부로 시각화할 수 있습니다. 이는 꽤 유용한 기능이므로, 나중에 그 방법을 자세히 설명하겠습니다.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="실습: 신뢰구간 구하기">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
실습: 신뢰구간 구하기
</div>
</div>
<div class="callout-body-container callout-body">
<p>이 실습을 하려면 <a href="03-Getting-started-with-jamovi.html#tip-ex-add-modules" class="quarto-xref">Tip&nbsp;<span>3.1</span></a> 을 수행하여 <code>lsj-data</code> 모듈이 설치되어 있어야 합니다.</p>
<ol type="1">
<li><p>‘파일’-‘열기’-’데이터 라이브러리’를 메뉴에서 선택합니다. 그러면 ’learning statistics with jamovi’라는 폴더가 보일 것입니다. 이 폴더를 선택합니다. 이미 이전 실습에서 이 폴더를 선택했으면 바로 이 폴더가 열릴 수도 있습니다.</p></li>
<li><p>데이터 라이브러리 목록에서 ’IQ sim’을 선택합니다.</p></li>
<li><p>‘탐구’-’기술통계’를 선택합니다.</p></li>
<li><p>왼편의 ‘기술통계’ 패널에서 <code>IQsim</code>를 ‘변수’ 상자에 넣습니다.</p></li>
<li><p>‘통계’ 옵션의 ’평균 분산’에 있는 ’평균에 대한 표준오차’와 ’평균에 대한 신뢰구간’을 체크 합니다. 그러면 결과 창의 기술통계 부분에 표준 오차와 신뢰구간의 하한과 상한 값이 나타납니다.</p></li>
<li><p>‘평균에 대한 신뢰구간’ 오른편에 있는 95%라는 수치를 90% 또는 99%로 바꾸어 신뢰구간의 상한과 하한이 어떻게 변화하는지 살펴봅니다.</p></li>
</ol>
<div class="cell enlarge-image" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="images/kor/fig8-ex1-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="요약" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="요약"><span class="header-section-number">8.6</span> 요약</h2>
<p>이 장에서는 두 가지 주요 주제를 다루었습니다. 장의 전반부에서는 표본 이론에 대해 설명하고, 후반부에서는 이 표본 이론을 활용하여 모집단의 모수를 추정하는 방법에 대해 다루었습니다. 절 구분은 다음과 같습니다:</p>
<ul>
<li><a href="#표본-모집단-및-표본추출">표본, 모집단 및 표본추출</a>에 대한 기본 개념</li>
<li>표본의 통계 이론: <a href="#대수의-법칙">대수의 법칙</a>과 <a href="#표본-분포와-중심극한정리">표본 분포와 중심극한정리</a></li>
<li><a href="#모집단-모수-추정하기">모집단 모수 추정하기</a>. 평균과 표준편차</li>
<li><a href="#sec-Estimating-a-confidence-interval">신뢰구간 추정</a></li>
</ul>
<p>항상 그렇듯이, 이 장에서는 표본추출과 추정과 관련된 모든 주제를 다루지는 않았지만, 심리학 입문 수업을 위한 내용으로는 꽤 포괄적이라고 생각합니다. 대부분의 응용 연구자들은 이보다 더 많은 이론이 필요하지 않을 것입니다. 이 장에서 다루지 않은 큰 질문 중 하나는 단순 무작위 표본추출이 아닌 경우에는 어떻게 해야 하는가입니다. 이러한 상황을 다루기 위한 다양한 통계 이론이 존재하지만, 이는 이 책의 범위를 벗어나는 내용입니다.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Keynes1923" class="csl-entry" role="listitem">
Keynes, J. M. (1923). <em>A tract on monetary reform</em>. Macmillan &amp; Company.
</div>
<div id="ref-Stigler1986" class="csl-entry" role="listitem">
Stigler, S. M. (1986). <em>The history of statistics</em>. Harvard University Press.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>엄밀한 수학적 의미에서 무작위성(randomness)을 정의하는 것은 매우 복잡하며, 이 책의 범위를 넘어섭니다. 따라서 여기에서는 기술적으로 엄격한 정의를 사용하지 않고, 동일한 과정을 반복할 때마다 다른 결과가 나올 가능성이 있다면 무작위성을 포함한 과정이라고 간주합니다.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>&lt;역주&gt; 저자의 표현이 정확하지는 않다. 모집단의 절대적 크기가 중요한 것이 아니라 표본의 크기에 비해 모잡단의 크기가 충분히 커야만 복원 표본추출과 비복원 추출의 차이가 무시될 수 있다. 모집단이 천 개의 개체로 구성되어 있다고 하더라도 표본의 크기가 천 개이면 복원 추출과 비복원 추출의 결과의 차이는 무시될 수 없다.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>현실은 그렇게 단순하지 않습니다. 사람을 “조현병 환자”와 “비(非)조현병 환자”라는 이분법적 범주로 나누는 것은 명확한 기준이 없는 경우가 많습니다. 그러나 이 책은 임상심리학 교재가 아니므로, 이러한 단순화를 이해해 주길 바랍니다.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>엄밀히 말하면, 대수의 법칙은 독립적인 값들의 평균으로 표현될 수 있는 모든 표본 통계량에 적용됩니다. 이는 확실히 표본 평균에는 적용됩니다. 그러나 다른 많은 표본 통계량 역시 특정 형태의 평균으로 표현될 수 있습니다. 예를 들어, 표본 분산도 일종의 평균으로 다시 쓸 수 있기 때문에 대수의 법칙이 적용됩니다. 그러나 표본의 최솟값은 어떤 형태로든 평균으로 표현될 수 없기 때문에 대수의 법칙이 적용되지 않습니다.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>평소처럼, 여기서 약간 대충 설명하고 있습니다. 중심극한정리는 이 섹션에서 암시하는 것보다 조금 더 일반적입니다. 대부분의 입문 통계 교재에서처럼, 저는 중심극한정리가 성립하는 한 가지 상황을 다루었습니다. 즉, 동일한 분포에서 추출된 다수의 독립적인 사건에 대해 평균을 구하는 경우입니다. 그러나 중심극한정리는 이보다 훨씬 더 광범위한 개념입니다. 예를 들어 “U-통계량(U-statistics)”이라는 전체 클래스가 있으며, 이들은 모두 중심극한정리를 만족하므로 큰 표본 크기에서 정규 분포를 따르게 됩니다. 평균(mean)은 이러한 통계량 중 하나이지만, 유일한 것은 아닙니다.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>실제로 이 질문에 관심이 있다면, 여기서 제가 설명하는 것보다 훨씬 더 신중해야 합니다. 와이알라의 IQ 점수를 포트 피리와 단순 비교하고 그 차이가 납 중독 때문이라고 가정할 수는 없습니다. 두 도시의 유일한 차이가 서로 다른 제련소 때문이라고 하더라도(사실 그렇지 않습니다), 사람들이 이미 납 오염이 인지 결손을 일으킨다고 믿고 있다는 사실을 고려해야 합니다.<br>
<a href="02-A-brief-introduction-to-research-design.html" class="quarto-xref"><span>Chapter 2</span></a> 절을 떠올려 보면, 이는 포트 피리 표본과 와이알라 표본 사이에 서로 다른 요구 효과(demand effects)가 존재한다는 의미입니다. 즉, 데이터에서 실제는 없는 집단 사이의 차이를 발견할 수 있으며, 이는 사람들이 “실제 차이”가 있다고 믿는 것 때문에 발생할 수 있습니다.<br>
연구자들이 실험복을 입고 IQ 테스트를 들고 포트 피리에 나타난다면, 현지인들이 여러분의 연구 목적을 눈치채지 못할 것이라고 생각하는 것은 매우 비현실적입니다. 일부 사람들은 연구에 협조적이지 않을 수 있고, 또 다른 사람들은 자신의 고향이 부정적으로 보이지 않도록 더 열심히 테스트에 임할 수도 있습니다.<br>
반면, 와이알라에서는 “철광석 오염”이라는 개념이 일반적이지 않기 때문에 이러한 동기 부여 효과가 상대적으로 약할 것입니다. 심리학 연구는 이렇게 복잡합니다.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>여기서 중요한 부분을 생략하고 있다는 점을 언급해야겠습니다. 불편추정량은 바람직한 특성이지만, 편향 외에도 중요한 요소들이 존재합니다. 다만 이 책의 범위를 벗어나므로 자세한 논의는 하지 않겠습니다. 단지 이 부분에 복잡성이 숨어 있음을 알려드리고자 합니다.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><span class="math inline">\(N-1\)</span>로 나누면 모집단 분산의 불편추정치를 얻을 수 있습니다:<br>
<span class="math display">\[\hat{\sigma}^2=\frac{1}{N-1}\sum_{i=1}^{N}(X_i - \bar{X})^2\]</span><br>
표준편차의 경우도 마찬가지입니다:<br>
<span class="math display">\[\hat{\sigma}=\sqrt{\frac{1}{N-1}\sum_{i=1}^{N}(X_i-\bar{X})^2}\]</span><br>
여기서 또 하나의 숨겨진 점이 있습니다. <span class="math inline">\(\hat{\sigma}^2\)</span>이 <span class="math inline">\(\sigma^2\)</span>의 불편추정량이라면, 제곱근을 취하면 <span class="math inline">\(\hat{\sigma}\)</span> 역시 <span class="math inline">\(\sigma\)</span>의 불편추정량일 거라고 생각하겠죠? 이상하게도 그렇지 않습니다. 실제로 <span class="math inline">\(\hat{\sigma}\)</span>에는 미묘한 편향이 존재합니다. 참으로 이상한 일입니다. <span class="math inline">\(\hat{\sigma}^2\)</span>는 모집단 분산 <span class="math inline">\(\sigma^2\)</span>의 편향 없는 추정량이지만, 제곱근을 취하면 <span class="math inline">\(\hat{\sigma}\)</span>는 모집단 표준편차 <span class="math inline">\(\sigma\)</span>의 편의추정량이 됩니다. 정말 기묘하죠? 왜 그럴까요? 기술적인 설명은 “비선형 변환(예: 제곱근)과 기댓값 연산은 교환되지 않기 때문”입니다. 다만 수학 통계학 강의를 듣지 않았다면 이 설명은 다소 어렵게 들릴 수 있습니다. 다행히도 실제로는 큰 문제가 되지 않습니다. 이 편향은 매우 작으며, 실제로는 모두 <span class="math inline">\(\hat{\sigma}\)</span>를 사용하고 잘 작동합니다. 때때로 수학은 참 성가시기도 합니다.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>이 인용구는 많은 티셔츠와 웹사이트에서 볼 수 있으며, 몇몇 학술 논문(예: <a href="https://jse.amstat.org/v10n3/friedman.html">https://jse.amstat.org/v10n3/friedman.html</a>)에서도 언급됩니다. 그러나 이 말의 정확한 출처는 찾을 수 없었습니다.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/kilhwan\.github\.io\/jamovi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-Introduction-to-probability.html" class="pagination-link" aria-label="확률이란?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">확률이란?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-Hypothesis-testing.html" class="pagination-link" aria-label="가설 검정">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">가설 검정</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="https://kilhwan.github.io/jamovi/">JAMOVI로 배우는 통계학</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/kilhwan/jamovi/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>